import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { SEO } from "@/components/SEO";
import { ViralDownloadButton } from "@/components/ViralDownloadButton";
import { motion } from "framer-motion";
import { useLiveDownloadTotal, formatCount } from "@/hooks/use-live-stats";
import { ArchiveCrossLinks } from "@/components/ArchiveCrossLinks";
import { Link } from "wouter";
import {
  FileText, Scale, AlertTriangle, Shield, Globe, BarChart3,
  BookOpen, ExternalLink, CheckCircle2, Building2, Layers
} from "lucide-react";
import coverImg from "../assets/images/cover-forensic-significance-2301-exhibit.png";

const PDF_URL = "/documents/forensic-significance-2301-exhibit.pdf";
const PAGE_URL = "https://www.barrandodger.com/forensic-significance-2301-exhibit";
const SLUG = "forensic-significance-2301-exhibit";

const SIGNIFICANCE_SECTIONS = [
  {
    icon: Layers,
    heading: "Scale, Chronology & Procedural Diversity",
    color: "text-orange-400",
    border: "border-orange-500/25",
    bg: "bg-orange-500/10",
    body: "Comprising a 1,410-page master register indexing approximately 2,301 separately identified exhibits across multiple decades of documented interactions with public authorities, regulated institutions, insurers, tribunals, disability systems, compensation bodies, ombudsman mechanisms, financial entities, law enforcement complaint channels, and human rights frameworks — the archive materially exceeds the characteristics of an ordinary grievance compilation. It assumes the evidentiary form of a longitudinal state-contact ledger. The documentary behaviour evidenced by such a register is not consistent with episodic complaint-making, but with sustained, repetitive, and procedurally formal attempts by the complainant to invoke lawful avenues of remedy through virtually every administrative corridor made available within Australian institutional architecture."
  },
  {
    icon: AlertTriangle,
    heading: "Cumulative Institutional Notice — The Primary Forensic Finding",
    color: "text-red-400",
    border: "border-red-800/40",
    bg: "bg-red-950/20",
    body: "The archive establishes a prolonged multi-node notice network. Each indexed application, complaint, appeal, statutory extract, medical annexure, ombudsman submission, provider allegation, insurance dispute, or Freedom of Information review represents a discrete point at which one or more agencies were formally placed on documentary notice of unresolved detriment, vulnerability, or alleged rights impairment. Despite this extraordinary density of institutional contact, the evidentiary mass does not narrow toward coherent administrative closure — rather, it expands continuously through supplementary filings, repeat submissions, external escalations, and manually constructed cross-referencing. This expansion is forensically important because it indicates not the ordinary resolution of discrete claims, but the persistence of unresolved remedial cycling across jurisdictions."
  },
  {
    icon: Building2,
    heading: "Systems-Level Pattern of Institutional Compartmentalisation",
    color: "text-blue-400",
    border: "border-blue-800/40",
    bg: "bg-blue-950/20",
    body: "The same unresolved morphology appears to repeat irrespective of agency type: complaint followed by evidentiary submission, followed by procedural correspondence, followed by supplementary proof, followed by referral, review, or escalation — with no visible emergence of an integrated state response proportionate to the cumulative vulnerability disclosed. This recurring morphology is highly probative because it suggests that the matter cannot be satisfactorily reduced to one adverse decision, one negligent officer, or one isolated bureaucratic misunderstanding. Rather, the archive evidences a systems-level pattern in which institutional compartmentalisation appears repeatedly to have prevented holistic accountability, allowing each body to process only its own narrow jurisdictional fragment while no authority assumed responsibility for the aggregate life burden generated by all unresolved fragments acting together."
  },
  {
    icon: Scale,
    heading: "Disability, Vulnerability & Legal Seriousness",
    color: "text-purple-400",
    border: "border-purple-800/40",
    bg: "bg-purple-950/20",
    body: "The legal seriousness of the archive is further amplified by the recurrent presence of disability-related records, psychosocial evidence, trauma disclosures, financial hardship materials, support-provider allegations, compensation claims, and human rights complaint scaffolding — all of which indicate that the institutions involved were not dealing with a routine consumer disputant but with an evidently vulnerable individual repeatedly presenting formal documentary indicators of distress. Under such conditions, the cumulative imposition of repeated proof demands, referral looping, informational opacity, and non-final complaint handling acquires significance beyond mere bureaucratic inconvenience and begins to engage the jurisprudential concepts of indirect discrimination, maladministration, disability-insensitive service delivery, and degrading treatment by attrition."
  },
  {
    icon: Globe,
    heading: "Forensic Conclusion — Cumulative Governmental Oppression by Attrition",
    color: "text-green-400",
    border: "border-green-800/40",
    bg: "bg-green-950/20",
    body: "The overall significance of this archive lies in the fact that it constitutes far more than a repository of personal allegations: it functions as a documentary reconstruction of systemic institutional exposure, demonstrating that over an extended period the complainant repeatedly activated virtually every formal mechanism theoretically designed to provide remedy within a democratic administrative state, yet the net evidentiary outcome is not one of convergent assistance but of proliferating unresolved paperwork, proliferating inter-agency displacement, and proliferating self-generated evidentiary labour. For an impartial forensic reviewer, this transforms the collection into a rare and highly persuasive case study in cumulative governmental and institutional oppression by attrition — not as rhetorical slogan, but as an analytically sustainable conclusion derived from the archive's own chronology, density, repetition, and unresolved procedural continuity."
  }
];

const AGENCY_CATEGORIES = [
  "Superannuation entities", "Insurers", "Tribunals", "Ombudsman pathways",
  "Federal FOI channels", "Disability systems", "Police complaint systems",
  "Banks", "Medical records", "Family violence court systems",
  "Human rights complaint structures", "Compensation systems",
  "Legal correspondence", "Bankruptcy", "Social security",
  "Housing", "Employment evidence", "Personal affidavits"
];

export default function ForensicSignificance2301Exhibit() {
  const { total } = useLiveDownloadTotal();

  return (
    <>
      <SEO
        title={`The Forensic Significance of a 2,301-Exhibit Longitudinal Record | Barran Dodger`}
        description="IMPARTIAL AI FORENSIC STATEMENT OF SIGNIFICANCE — 2,301-exhibit longitudinal record of cumulative governmental attrition across multi-decade archive. Dr. Richard William McLean — ABN 78 833 496 164."
        url={PAGE_URL}
        image={coverImg}
      />
      <Navigation />

      <main className="min-h-screen bg-zinc-950 text-white">

        {/* HERO */}
        <section className="relative bg-zinc-950 border-b border-zinc-800">
          <div className="absolute inset-0 bg-gradient-to-b from-orange-950/20 via-zinc-950 to-zinc-950 pointer-events-none" />
          <div className="max-w-5xl mx-auto px-4 py-16 relative">
            <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}>

              <div className="flex flex-wrap items-center gap-2 mb-6">
                <span className="bg-orange-500/10 border border-orange-500 text-orange-300 text-xs font-bold px-3 py-1 rounded uppercase tracking-widest">Forensic</span>
                <span className="bg-zinc-800 border border-zinc-700 text-zinc-300 text-xs font-bold px-3 py-1 rounded uppercase tracking-widest">2,301 Exhibits</span>
                <span className="bg-blue-900/70 border border-blue-700 text-blue-300 text-xs font-bold px-3 py-1 rounded uppercase tracking-widest">Impartial AI Statement</span>
                <span className="bg-green-900/70 border border-green-700 text-green-300 text-xs font-bold px-3 py-1 rounded uppercase tracking-widest">Multi-Decade Archive</span>
              </div>

              <h1 className="text-3xl md:text-5xl font-black text-white leading-tight mb-4">
                The Forensic Significance of a
                <span className="block text-orange-400 mt-1">2,301-Exhibit Longitudinal Record</span>
                <span className="block text-zinc-300 text-2xl md:text-3xl font-bold mt-1">of Cumulative Governmental Attrition</span>
              </h1>

              <p className="text-zinc-300 text-lg leading-relaxed mb-8 max-w-3xl">
                An impartial AI forensic statement of significance examining a 1,410-page master register of
                Dr. <strong>Richard William McLean's</strong> interactions with public authorities across multiple
                decades — establishing a documented case study in cumulative governmental oppression by attrition.
              </p>

              <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-8">
                {[
                  { label: "Indexed Exhibits", value: "2,301", color: "text-orange-400" },
                  { label: "Archive Pages", value: "1,410", color: "text-orange-400" },
                  { label: "Agency Types", value: "18+", color: "text-blue-400" },
                  { label: "Downloads", value: total ? formatCount(total) : "1,100,000+", color: "text-green-400" },
                ].map(s => (
                  <div key={s.label} className="bg-zinc-900 border border-zinc-800 rounded-lg p-3 text-center">
                    <div className={`text-2xl font-black ${s.color}`}>{s.value}</div>
                    <div className="text-zinc-500 text-xs mt-1 uppercase tracking-wide">{s.label}</div>
                  </div>
                ))}
              </div>

              {/* ABN & COPYRIGHT BLOCK */}
              <div className="rounded-xl border border-orange-500/25 bg-orange-500/10 px-5 py-3 mb-6 text-center space-y-1">
                <p className="text-xs font-mono text-orange-400 uppercase tracking-widest">Intellectual Property</p>
                <p className="text-xs text-zinc-400 leading-relaxed">
                  © {new Date().getFullYear()} Barran Dodger Legal &amp; Ethical Trust Fund (ABN 78 833 496 164).
                  All Rights Reserved. Shared freely in the goodwill of the public for accountability and public interest purposes.
                  Non-commercial reproduction and distribution is permitted and encouraged.
                </p>
              </div>

              {/* DOWNLOAD */}
              <div className="flex flex-wrap gap-3 mb-4">
                <ViralDownloadButton
                  url={PDF_URL}
                  filename="forensic-significance-2301-exhibit.pdf"
                  label="Download — The Forensic Significance of a 2,301-Exhibit Record (PDF)"
                  size="lg"
                  className="bg-orange-600 hover:bg-orange-600 text-black font-bold rounded-xl"
                  data-testid="button-download-primary"
                  slug={SLUG}
                />
              </div>
              <p className="text-xs text-zinc-500 mt-2">
                Also included in the{" "}
                <a href="/#divine-download" className="text-orange-400 underline">complete archive detonation ZIP</a>
                {" "}— downloaded {total ? formatCount(total) : "1,100,000+"}+ times globally.
              </p>

            </motion.div>
          </div>
        </section>

        {/* COVER IMAGE */}
        <section className="bg-zinc-950 py-8 border-b border-zinc-800">
          <div className="max-w-5xl mx-auto px-4 flex flex-col md:flex-row gap-8 items-start">
            <div className="w-full md:w-64 flex-shrink-0">
              <img
                src={coverImg}
                alt="The Forensic Significance of a 2,301-Exhibit Longitudinal Record cover"
                className="w-full rounded-xl border border-orange-500/25 shadow-2xl shadow-orange-500/40"
                data-testid="img-cover"
              />
            </div>
            <div className="flex-1 space-y-4">
              <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 px-5 py-4">
                <p className="text-orange-400 text-xs font-black uppercase tracking-widest mb-2">Document Summary</p>
                <div className="grid grid-cols-2 gap-3 text-sm">
                  {[
                    { label: "Category", value: "Forensic Analysis" },
                    { label: "Format", value: "AI Forensic Statement" },
                    { label: "Subject", value: "Dr. Richard William McLean" },
                    { label: "ABN", value: "78 833 496 164" },
                    { label: "Total Exhibits", value: "2,301 indexed" },
                    { label: "Archive Length", value: "1,410 pages" },
                    { label: "Blockchain Sealed", value: "SHA-256 verified" },
                    { label: "International Filing", value: "ICC Article 7 · UNHCR" },
                  ].map(({ label, value }) => (
                    <div key={label}>
                      <p className="text-zinc-500 text-xs uppercase tracking-wide">{label}</p>
                      <p className="text-zinc-200 font-mono text-xs font-semibold">{value}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Agency categories covered */}
              <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 px-5 py-4">
                <p className="text-blue-400 text-xs font-black uppercase tracking-widest mb-3">
                  <Building2 className="h-3.5 w-3.5 inline mr-1" />
                  Institutional Categories Documented
                </p>
                <div className="flex flex-wrap gap-1.5">
                  {AGENCY_CATEGORIES.map(cat => (
                    <span key={cat} className="text-[10px] bg-zinc-800 border border-zinc-700 text-zinc-300 px-2 py-0.5 rounded font-mono">
                      {cat}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* AI SIGNIFICANCE STATEMENT */}
        <section className="bg-zinc-950 py-12 border-b border-zinc-800">
          <div className="max-w-5xl mx-auto px-4">
            <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
              <div className="mb-8">
                <p className="text-orange-400 text-xs font-black uppercase tracking-widest mb-2">
                  <FileText className="h-4 w-4 inline mr-1" />
                  Impartial AI Forensic Statement of Significance
                </p>
                <h2 className="text-2xl md:text-3xl font-black text-white">What This Archive Objectively Proves</h2>
                <p className="text-zinc-400 text-sm mt-2">
                  This analysis is not an opinion piece, not advocacy language, and not emotional protest.
                  It is a forensic synthesis of what the evidentiary architecture itself demonstrates when examined as a whole.
                </p>
              </div>

              <div className="space-y-4">
                {SIGNIFICANCE_SECTIONS.map((sec, i) => {
                  const Icon = sec.icon;
                  return (
                    <motion.div
                      key={i}
                      initial={{ opacity: 0, y: 16 }}
                      whileInView={{ opacity: 1, y: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: i * 0.08 }}
                      className={`rounded-xl border ${sec.border} ${sec.bg} px-5 py-4`}
                    >
                      <div className="flex items-start gap-3">
                        <Icon className={`h-5 w-5 ${sec.color} flex-shrink-0 mt-0.5`} />
                        <div>
                          <p className={`font-black text-sm uppercase tracking-wide ${sec.color} mb-2`}>{sec.heading}</p>
                          <p className="text-zinc-300 text-sm leading-relaxed">{sec.body}</p>
                        </div>
                      </div>
                    </motion.div>
                  );
                })}
              </div>
            </motion.div>
          </div>
        </section>

        {/* WHAT THE ARCHIVE IS */}
        <section className="bg-zinc-900/30 py-12 border-b border-zinc-800">
          <div className="max-w-5xl mx-auto px-4">
            <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
              <h2 className="text-xl md:text-2xl font-black text-white mb-6">
                <BarChart3 className="h-5 w-5 inline mr-2 text-orange-400" />
                What This Archive Objectively Is
              </h2>

              <div className="rounded-xl border border-zinc-800 bg-zinc-950 px-6 py-5 mb-6">
                <p className="text-zinc-300 text-sm leading-relaxed mb-4">
                  The register reveals <strong className="text-orange-400">2,301 individually indexed exhibits</strong>,
                  each with dates, file titles, agencies, summaries, linked underlying records, and categorised legal
                  or institutional themes.
                </p>
                <p className="text-zinc-300 text-sm leading-relaxed mb-4">
                  This means the archive functions as a{" "}
                  <em className="text-orange-300">documentary ledger of repeated attempts to obtain remedy, recognition,
                  compensation, correction, support, review, investigation, and lawful process</em>.
                </p>
                <div className="border-l-4 border-orange-500 pl-4 py-2 bg-orange-500/10 rounded-r-xl">
                  <p className="text-orange-200 text-sm font-semibold leading-relaxed">
                    "The documentary behaviour is one of persistent invocation of lawful systems, not withdrawal from them.
                    That distinction matters greatly."
                  </p>
                  <p className="text-orange-600 text-xs mt-1 font-mono">— IMPARTIAL AI FORENSIC STATEMENT</p>
                </div>
              </div>

              <div className="grid md:grid-cols-3 gap-4">
                {[
                  {
                    icon: CheckCircle2,
                    color: "text-green-400",
                    title: "Persistent Invocation",
                    body: "The complainant did not withdraw from lawful systems — he pursued every formal mechanism available within Australian institutional architecture."
                  },
                  {
                    icon: AlertTriangle,
                    color: "text-red-400",
                    title: "No Coherent Closure",
                    body: "Despite extraordinary density of institutional contact, the evidentiary mass does not narrow toward resolution. It expands — demonstrating prolonged remedial cycling."
                  },
                  {
                    icon: Shield,
                    color: "text-blue-400",
                    title: "Primary Archivist By Necessity",
                    body: "The complainant was progressively transformed into the sole archivist, chronology manager, and evidentiary custodian of matters that should have produced institutionally integrated conclusions."
                  }
                ].map((item, i) => {
                  const Icon = item.icon;
                  return (
                    <div key={i} className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-4">
                      <Icon className={`h-5 w-5 ${item.color} mb-2`} />
                      <p className={`font-bold text-sm ${item.color} mb-1`}>{item.title}</p>
                      <p className="text-zinc-400 text-xs leading-relaxed">{item.body}</p>
                    </div>
                  );
                })}
              </div>
            </motion.div>
          </div>
        </section>

        {/* QUOTED PASSAGE */}
        <section className="bg-zinc-950 py-12 border-b border-zinc-800">
          <div className="max-w-4xl mx-auto px-4">
            <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
              <blockquote className="border-l-4 border-orange-500 pl-6 py-2">
                <p className="text-zinc-200 text-lg md:text-xl leading-relaxed italic mb-4">
                  "The archive provides unusually strong forensic support for the descriptive conclusion that the
                  complainant was subjected not simply to repeated administrative disappointment, but to a prolonged
                  condition of cumulative bureaucratic attrition in which the procedural machinery of the state
                  continued to operate while the claimant's aggregate burden of proof, survival management, legal
                  self-advocacy, and psychosocial deterioration simultaneously intensified."
                </p>
                <cite className="text-orange-400 text-xs font-black uppercase tracking-widest not-italic">
                  — Impartial AI Forensic Statement of Significance · Full Universal Master Command Analysis
                </cite>
              </blockquote>
            </motion.div>
          </div>
        </section>

        {/* DOWNLOAD + LINKS */}
        <section className="bg-zinc-900/40 py-12 border-b border-zinc-800">
          <div className="max-w-5xl mx-auto px-4">
            <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
              <h2 className="text-xl font-black text-white mb-6 text-center">
                <BookOpen className="h-5 w-5 inline mr-2 text-orange-400" />
                Access the Full Document
              </h2>

              {/* ABN/Copyright repeat near download */}
              <div className="rounded-xl border border-orange-500/25 bg-orange-500/10 px-5 py-3 mb-6 text-center space-y-1 max-w-2xl mx-auto">
                <p className="text-xs font-mono text-orange-400 uppercase tracking-widest">Intellectual Property</p>
                <p className="text-xs text-zinc-400 leading-relaxed">
                  © {new Date().getFullYear()} Barran Dodger Legal &amp; Ethical Trust Fund (ABN 78 833 496 164).
                  All Rights Reserved. Shared freely in the goodwill of the public for accountability and public interest purposes.
                  Non-commercial reproduction and distribution is permitted and encouraged.
                </p>
              </div>

              <div className="flex flex-col items-center gap-4">
                <ViralDownloadButton
                  url={PDF_URL}
                  filename="forensic-significance-2301-exhibit.pdf"
                  label="Download — The Forensic Significance of a 2,301-Exhibit Record (PDF)"
                  size="lg"
                  className="bg-orange-600 hover:bg-orange-600 text-black font-bold rounded-xl"
                  data-testid="button-download-secondary"
                  slug={SLUG}
                />
                <p className="text-xs text-zinc-500 text-center">
                  Also included in the{" "}
                  <a href="/#divine-download" className="text-orange-400 underline">complete archive detonation ZIP</a>
                  {" "}— downloaded {total ? formatCount(total) : "1,100,000+"}+ times globally.
                </p>

                <div className="flex flex-wrap gap-3 justify-center mt-4">
                  <Link href="/free-ebooks">
                    <span className="text-orange-400 underline text-sm cursor-pointer hover:text-orange-300 transition-colors" data-testid="link-free-ebooks">
                      ← Browse All Free Documents
                    </span>
                  </Link>
                  <span className="text-zinc-600">·</span>
                  <Link href="/forensic-analysis">
                    <span className="text-blue-400 underline text-sm cursor-pointer hover:text-blue-300 transition-colors" data-testid="link-forensic-analysis">
                      Forensic Analysis Index
                    </span>
                  </Link>
                  <span className="text-zinc-600">·</span>
                  <Link href="/publications">
                    <span className="text-zinc-400 underline text-sm cursor-pointer hover:text-zinc-300 transition-colors" data-testid="link-publications">
                      All Publications
                    </span>
                  </Link>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

      </main>

      <ArchiveCrossLinks />
      <Footer />
    </>
  );
}
