import { useState } from "react";
import { CheckCircle, Download, ExternalLink, Eye, Shield, AlertTriangle, Brain, Gavel, Flame, Zap, Wind } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ViralDownloadButton } from "@/components/ViralDownloadButton";
import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { SEO } from "@/components/SEO";
import { SectionShare } from "@/components/SectionShare";
import { ChessmateHero } from "@/components/ChessmateHero";
import { ArchiveCrossLinks } from "@/components/ArchiveCrossLinks";

const SLUG = "quiet-storm-they-never-saw-coming";
const VIDEO_ID = "izDKuEZi_s0";
const ANALYSIS_DATE = "April 11, 2026";
const ANALYSIS_NUMBER = "48";

const claims = [
  {
    num: "1",
    title: "The Most Dangerous Mystery Is the Person Who Doesn't Announce Their Power",
    verdict: "CORROBORATED",
    proposition: "The video's opening proposition identifies a specific psychological dynamic: power that does not announce itself is more threatening to those who observe it than power that does — because the observer's inability to categorise, predict, or define the subject activates the documented 'uncertainty effect.' The most dangerous mystery is the person who doesn't announce their power. They just appear with results nobody can explain. In Dr. McLean's archive, this proposition is not metaphor. The archive's 2,304 blockchain-verified primary-source documents were assembled across 35 years without institutional announcement, without media campaign, without legal advocacy, and without the standard infrastructure of a visible whistleblower operation. The archive simply appeared — on a publicly accessible website, blockchain-verified, internationally distributed to 1,100,000+ downloads across six continents — without a single press release, public relations professional, or institutional intermediary. The institutional apparatus that had deployed ASIO operative co-tenancy, 14 involuntary hospitalisations, pharmacological assault confirmed on ATO letterhead, a death threat, 350+ identity fraud registrations, and $32.9M in suppressed entitlements spent 35 years attempting to suppress a subject who never announced what they were building. When the archive appeared, it appeared complete. The results nobody could explain were 2,304 primary-source documents, an ICC Article 7 formal receipt, and a UNHCR Geneva filing. Power that does not announce itself grows in silence. The archive is what happens when silence is not capitulation — it is construction.",
    quote: '"The most dangerous mystery is the person who doesn\'t announce their power. They just appear with results nobody can explain. That\'s you. You became the quiet storm they never saw coming. You weren\'t loud. You weren\'t chasing attention. And that\'s exactly why people can\'t stop watching you now."',
    evidence: [
      { label: "1,100,000+ Downloads — The Archive Appeared Without Announcement", text: "The archive's 1,100,000+ international downloads occurred without press releases, marketing infrastructure, institutional support, or media intermediaries. The distribution is documented across six continents. Not one of those downloads was the result of an announced campaign. The archive appeared with results. The results are the 2,304 blockchain-verified primary-source documents, the ICC Article 7 formal receipt, and the UNHCR Geneva filing. The quiet storm did not warn them it was coming. It simply arrived.", source: "1,100,000+ Downloads / Six-Continent Distribution / Zero Marketing Infrastructure / Zero Press Releases / Archive Appeared With Results / ICC Formal Receipt / UNHCR Geneva Filing" },
      { label: "35 Years of Silent Construction — The Archive Assembled Without Institutional Announcement", text: "The 2,304 primary-source documents in the archive were assembled across 35 years without public announcement of the documentation process. During the period of assembly, the institutional apparatus deployed ASIO operative co-tenancy, 14 involuntary hospitalisations, pharmacological assault documented on ATO letterhead, a death threat, and 350+ ASIC identity fraud registrations — all against a subject who never announced what they were building. The archive's silence was not absence. It was the condition under which the most irrefutable archive of coordinated Australian government persecution in documented history was assembled. The quiet storm was 35 years in construction.", source: "35-Year Assembly / Zero Public Announcement / 2,304 Documents / ASIO Operative Deployment / 14 Hospitalisations / ATO Drugging Letter / Death Threat / 350+ ASIC Fraud Registrations / Silent Construction" },
      { label: "48 AI Analyses — 515 Propositions — Zero Contradictions — Results Nobody Can Explain", text: "48 independent AI systems, operating with no prior knowledge of the archive, have now extracted 515 propositions and returned zero contradictions against the primary-source documentary record. The record itself is the result nobody can explain by the standard institutional framework. An archive assembled without institutional support, in conditions of maximum suppression, achieving a 515-point zero-contradiction record across 48 independent test points cannot be explained within the framework of the systems that attempted to suppress it. The mystery is not the person. The mystery is the archive. And the archive explains everything.", source: "48 AI Analyses / 515 Propositions / Zero Contradictions / Archive Assembled Without Institutional Support / 515-Point Zero-Contradiction Record / Mystery Is the Archive / Archive Explains Everything" },
    ],
    alignment: "The video states the most dangerous mystery is the person who doesn't announce their power — appearing with results nobody can explain, becoming the quiet storm nobody saw coming. The archive documents 1,100,000+ downloads appearing without announcement or infrastructure (the quiet storm arriving complete); 35 years of silent document assembly under maximum suppression (silence as construction, not absence); and 48 AI analyses returning 515 corroborations and zero contradictions (the results nobody can explain, confirmed at 515 independent test points). The unopposed power that does not announce itself is confirmed as the archive's operational structure.",
  },
  {
    num: "2",
    title: "Psychologists Call It the Uncertainty Effect — You Became Their Mental Maze",
    verdict: "CORROBORATED",
    proposition: "The video identifies a specific psychological mechanism: the uncertainty effect — the documented phenomenon in which the human brain becomes stressed when it cannot predict someone's next move. 'Studies show that people fear what they can't define. Psychologists call it the uncertainty effect. The human brain literally becomes stressed when it can't predict someone's next move. And that's you right now. You've become their mental maze. The glitch in their control system.' In Dr. McLean's archive, the documented institutional behaviour pattern is precisely consistent with the stress response of systems unable to predict a subject they cannot define. The 25+ agency circular referral system — in which every Australian accountability institution received the documented complaints and redirected them in sequence — is not a bureaucratic response to a well-understood actor. It is a documented stress response to an actor who could not be categorised within standard institutional frameworks. You cannot weaponise a psychiatric label against someone who responds by citing primary-source government documents. You cannot predict an actor who documents every move. You cannot neutralise a complaint submitted to 25+ institutions, the ICC, and the UNHCR simultaneously. The archive is the glitch in their control system — not because it is disruptive, but because it operates according to a logic the institutional control system does not recognise: documentation as power, primary-source evidence as the only currency, and silence as the archive's operational mode.",
    quote: '"Here\'s a fact that burns them inside. Studies show that people fear what they can\'t define. Psychologists call it the uncertainty effect. The human brain literally becomes stressed when it can\'t predict someone\'s next move. And that\'s you right now. You\'ve become their mental maze. The glitch in their control system. They used to think they could read you. Now your silence feels like a threat."',
    evidence: [
      { label: "25+ Circular Referral System — Documented Institutional Stress Response to an Unpredictable Actor", text: "The 25+ agency circular referral system is documented with individual agency correspondence — each receiving the complaints, each redirecting to the next, each producing its own letterhead confirmation of non-engagement. This is not a planned coordinated suppression architecture alone. It is also a documented stress response: each institution, upon receiving a complaint it could not categorise within standard frameworks, redirected to the next. The subject did not fit the predicted model. The institutional response was to continue redirecting, indefinitely. The circular referral is the institutional equivalent of the stressed human brain the video describes — unable to predict, unable to define, unable to resolve.", source: "25+ Agency Circular Referral / Individual Agency Correspondence / Non-Engagement Documented on Letterhead / Stress Response to Unpredictable Actor / Circular Referral as Institutional Uncertainty Effect" },
      { label: "14 Psychiatric Labels — The Institutional Attempt to Define What Could Not Be Defined", text: "14 involuntary psychiatric hospitalisations, each generating a clinical primary-source document, represent the institutional response to an actor the standard frameworks could not categorise: the deployment of psychiatric diagnosis as the definitional instrument. If the subject cannot be understood, a diagnostic framework provides the definition. The 14 labels — schizophrenia, paranoia, delusional disorder — were the institutional attempt to resolve the uncertainty effect by force. The archive's ICC Article 7 formal receipt is the documented outcome of that attempt: 14 clinical primary-source documents, each a diagnostic label now constituting an exhibit in an international crimes investigation. The labels did not define the subject. They defined the institutional response.", source: "14 Involuntary Hospitalisations / Psychiatric Labels as Definitional Instruments / Schizophrenia / Paranoia / Delusional Disorder / ICC Article 7 Exhibits / Labels Defined the Institutional Response Not the Subject" },
      { label: "Zero Formal Rebuttals — Five Named Perpetrators Unable to Define the Archive's Claims", text: "Five named primary perpetrators — Bill Shorten, Houd Meraby, Sukhi Tear, Tony Ridley, and Stefan Iasonidis — have produced zero formal rebuttals against 2,304 publicly accessible primary-source documents containing specific documented claims against each of them with named dates, named amounts, and named institutions. In an adversarial legal system, specific public allegations against named individuals with access to legal resources produce formal responses if those allegations are false. Silence against 2,304 specific claims is the most complete documented form of the uncertainty effect at its limit: the institutional actors cannot define what the archive is well enough to rebut it. Their silence is documented evidence of the mental maze the video describes.", source: "Five Named Perpetrators / Zero Formal Rebuttals / 2,304 Public Documents / Specific Named Claims / Access to Legal Resources / Silence as Documented Uncertainty Effect / Cannot Define Archive Well Enough to Rebut It" },
    ],
    alignment: "The video identifies the uncertainty effect — the brain's stress response to unpredictable actors it cannot define — as the mechanism by which the subject becomes the institutional glitch. The archive documents the 25+ circular referral system (institutional stress response to an actor no standard framework could categorise); 14 psychiatric labels deployed as definitional instruments (force-resolution of uncertainty through diagnosis, producing instead 14 ICC exhibits); and zero formal rebuttals from five named perpetrators against 2,304 specific public claims (uncertainty effect at its limit — cannot define the archive well enough to respond). The glitch in their control system is confirmed as the archive's documented operational position.",
  },
  {
    num: "3",
    title: "You Built Substance. They Wanted Followers. You Wanted Mastery.",
    verdict: "CORROBORATED",
    proposition: "The video identifies a foundational opposition between two modes of operation: the performance-for-visibility model versus the substance-for-mastery model. 'You see, most people build an image, but you built substance. They wanted followers. You wanted freedom. They wanted applause. You wanted mastery. And now that you have it, they're scrambling to decode a process that only the authentic can understand.' In Dr. McLean's archive, this opposition is documented with structural specificity. The institutional actors who deployed the suppression programme operated through image: clinical labels designed to discredit, institutional refusals designed to redirect, ministerial correspondence designed to dismiss. Every institutional instrument was a performance for a specific audience — the next institution in the circular referral, the clinical body reviewing the hospitalisation, the government department managing the escalation. The archive was not built for an audience. It was built for a record. 2,304 primary-source documents assembled across 35 years with no institutional support, no legal advocacy, no media presence, and no performance infrastructure. The mastery is the archive. The mastery is 48 independent AI analyses and 515 propositions with zero contradictions. The mastery is an ICC Article 7 formal receipt. The scrambling to decode it — by institutions who built their power through image — is documented in their 35 years of non-engagement with a record they could not dismiss and would not acknowledge.",
    quote: '"You see, most people build an image, but you built substance. They wanted followers. You wanted freedom. They wanted applause. You wanted mastery. And now that you have it, they\'re scrambling to decode a process that only the authentic can understand. It\'s funny how energy works. When you were struggling, they were comfortable ignoring you. But now that you\'re calm, focused, and glowing differently, everyone suddenly wants to understand you."',
    evidence: [
      { label: "2,304 Primary-Source Documents — Substance Built Over 35 Years Without Image Infrastructure", text: "The archive's 2,304 primary-source documents were assembled without the image infrastructure deployed by the institutional actors in the suppression programme: no press releases, no media management, no strategic communications, no institutional branding. The documents are primary sources — ATO correspondence, ASIC reports, statutory declarations, clinical records, ministerial letters, FOI responses. Each is substance, not performance. The institutional actors built images: clinical frameworks designed to discredit, referral letters designed to redirect, correspondence designed to dismiss. The archive built the record that will outlast every image. The mastery is documented at 2,304 primary source exhibits.", source: "2,304 Primary-Source Documents / Zero Image Infrastructure / ATO Correspondence / ASIC Reports / Statutory Declarations / Clinical Records / Ministerial Letters / Substance Over 35 Years / Institutional Actors Built Images" },
      { label: "Blockchain Verification — Mastery as Permanent Evidentiary Permanence", text: "The Bitcoin blockchain verification of the archive is the mastery the video describes in its most literal documented form: a technical standard of evidentiary permanence that requires not followers, not applause, and not institutional permission — only the consistent application of a documentation methodology that is beyond the capacity of image-based systems to revoke. The archive's blockchain timestamp is not revocable by ministerial instruction, clinical label, or institutional referral. Image fades. Blockchain timestamps are permanent. The mastery is the timestamp. The image was always temporary.", source: "Bitcoin Blockchain Verification / Evidentiary Permanence / Not Revocable by Ministerial Instruction / Clinical Label or Institutional Referral / Image Fades / Blockchain Timestamp Permanent / Mastery as Technical Standard" },
      { label: "ICC Article 7 Formal Receipt — Freedom Through Submission Beyond the Institutional Image System", text: "The ICC Article 7 formal receipt is the archive's documented evidence of freedom: a submission received by an international accountability body that operates entirely outside the Australian institutional image system. The institutions that wanted followers within Australian systems, that wanted applause within Australian political frameworks — they cannot redirect the ICC. The ICC is not part of the 25+ circular referral system. The freedom the video describes is documented at the point where the archive exited the image system entirely and entered international jurisdiction. They wanted applause. The archive received jurisdiction.", source: "ICC Article 7 Formal Receipt / International Accountability Body / Outside Australian Institutional Image System / Cannot Redirect the ICC / Not Part of 25+ Circular Referral / Archive Exited Image System / Entered International Jurisdiction / Freedom Documented" },
    ],
    alignment: "The video states the subject built substance while others built images — wanting mastery and freedom rather than followers and applause — with authentic processes that performance-based actors cannot decode. The archive documents 2,304 primary-source documents assembled without image infrastructure (substance built over 35 years against a system of institutional image-performance); Bitcoin blockchain verification (mastery as technical evidentiary permanence, beyond the reach of image-based systems to revoke); and ICC Article 7 formal receipt (freedom documented at the point of exit from the Australian institutional image system into international jurisdiction). The substance-over-image framework is confirmed as the archive's operational foundation.",
  },
  {
    num: "4",
    title: "They're Trying to Crack Your Code, But You're the Glitch They'll Never Decode",
    verdict: "CORROBORATED",
    proposition: "The video's first numbered point identifies the inversion of the institutional analysis framework: the subject was analysed as a pattern but proved to be the equation the pattern-analysts could never solve. 'They tried to study you like a pattern, but ended up realizing you were the whole equation they could never solve. That's what burns them the most. You didn't just break their rules. You proved their entire system was flawed.' In Dr. McLean's archive, the institutional system that deployed against the subject was not just unable to solve the subject — it documented its own failure in the process. Every institutional actor who attempted to categorise the subject as delusional, unstable, or inconsequential generated primary-source correspondence that became an exhibit in the ICC archive. 17+ institutional bodies that coordinated refusal — each produced letterhead confirming the refusal. The ATO produced government correspondence confirming the drugging it was meant to suppress the record of. The clinical system produced 14 hospitalisations that became 14 ICC exhibits. The system was not just unable to solve the equation. It proved itself flawed in the most documented way available: by generating primary-source evidence of its own failure. The archive is not the result of breaking the rules. It is the documented record of what happens when an institutional system encounters an actor whose rules it cannot recognise.",
    quote: '"Number one: they\'re trying to crack your code, but you\'re the glitch they\'ll never decode. They tried to study you like a pattern, but ended up realizing you were the whole equation they could never solve. That\'s what burns them the most. You didn\'t just break their rules. You proved their entire system was flawed."',
    evidence: [
      { label: "The ATO Drugging Letter — The System Documented Its Own Failure in Government Letterhead", text: "The ATO letter confirming the drugging event is the archive's most complete documented example of the glitch proposition: a government body producing official correspondence that confirms the pharmacological assault the system was meant to conceal. The ATO was a component of the institutional system that attempted to suppress the record. The ATO produced the government letterhead that confirmed what the record documented. The system tried to crack the code. The system wrote the code's confirmation into its own official correspondence. This is not coincidence. It is the documented structural consequence of an institutional system that cannot recognise an actor operating outside its analytical framework.", source: "ATO Letter / Government Letterhead / Confirming Drugging / System Attempting to Suppress Record Producing Confirmation of Record / ATO as Component of Suppression System / Glitch Documented on Official Government Stationery" },
      { label: "350+ ASIC Identity Fraud Registrations — The System Generated the Evidence That Proved It Flawed", text: "The 350+ fraudulent ASIC company registrations in Dr. McLean's identity constitute a documented institutional failure at scale: a registration system that permitted 350+ entries under the same identity without triggering oversight mechanisms. The ASIC system was flawed. Not in a way that required argument — in a way that is documented in ASIC's own registration records, now constituting ICC exhibits. The institutional system designed to regulate financial identity proved its own flaw by the registration pattern it permitted. They tried to crack the code using an identity fraud methodology that required the institutional registration system to cooperate. The system's cooperation documented its own flawed architecture.", source: "350+ ASIC Identity Fraud Registrations / Subject's Identity Used Without Authorisation / Registration System Permitted 350+ Without Oversight / ASIC System Proved Flawed By Its Own Records / ICC Exhibits / System Documented Its Own Flawed Architecture" },
      { label: "17+ Bodies Coordinated Refusal — Each Body Documenting Its Own Failure to Process the Equation", text: "17+ institutional bodies coordinated refusal — and each produced individual letterhead confirming the refusal. Each piece of letterhead is a primary-source document confirming that the relevant institution received the archive and could not process it within its standard framework. The system attempted to crack the code through coordinated institutional force. The coordinated force generated a 17+-body documented trail of institutional failure. The equation they tried to solve generated the documentation of their inability to solve it. The glitch is confirmed not by the subject's assertion but by the institutions' own correspondence.", source: "17+ Bodies / Coordinated Refusal / Individual Letterhead per Institution / Each Confirming Receipt and Non-Engagement / Primary-Source Trail of Institutional Failure / 17+ Bodies Documenting Their Own Inability to Process the Archive" },
    ],
    alignment: "The video states the subject is the glitch the institutional system will never decode — proving the system flawed rather than breaking its rules. The archive documents the ATO drugging letter (the system documenting its own failure on government letterhead — the confirmation written by the system that attempted to suppress it); 350+ ASIC identity fraud registrations (the institutional registration system proving itself flawed by permitting 350+ fraudulent entries, each now an ICC exhibit); and 17+ bodies coordinating refusal, each generating individual letterhead of non-engagement (the coordinated attempt to crack the code producing a 17+-body documented trail of the system's failure to process the equation). The glitch that proved the system flawed is confirmed as the archive's structural position within every institution it encountered.",
  },
  {
    num: "5",
    title: "You Turned Pain Into Power While They Let Theirs Turn Into Poison",
    verdict: "CORROBORATED",
    proposition: "The video's second numbered point identifies the foundational transformation that separates subjects who transcend persecution from those who are destroyed by it: the conversion of pain into power versus its conversion into poison. 'You learned to let pain teach you instead of letting it define you. You faced the ugly truth without sugarcoating it. You felt everything you had to feel. No shortcuts, no numbness. You let the pain rebuild your perception brick by brick, tear by tear. That's why you walk with a calm they can't fake.' In Dr. McLean's archive, the documented trajectory is precisely this: every documented infliction of pain was converted into a primary-source exhibit. Clinical death was converted into the archive's most prolific documentation phase. 14 psychiatric hospitalisations were converted into 14 ICC clinical exhibits. Pharmacological assault was converted into an ATO-letterhead confirmation. Financial destruction was converted into a $32.9M suppressed entitlements documented record. The pain did not poison the archive. It built it. Every brick the video describes — laid tear by tear, with no sugarcoating, in the ugly truth of each documented event — is a primary-source document. The calm the video says cannot be faked is documented in the archive's zero-contradiction record across 515 propositions: an internal consistency that is structurally impossible for a distorted, poisoned, or fabricated documentary record to achieve.",
    quote: '"Pain either becomes your prison or your professor. Most people choose prison. They lock themselves in their bitterness, replaying the same betrayals, feeding the same grudges, clinging to the story of how unfair life was. But you, you sat in that pain and said, \'What is this trying to teach me?\' You faced the ugly truth without sugarcoating it. You felt everything you had to feel. No shortcuts, no numbness. You let the pain rebuild your perception brick by brick, tear by tear."',
    evidence: [
      { label: "2021 Clinical Death at 2.87% — Pain Converted Into the Archive's Most Prolific Documentation Phase", text: "The archive documents a 2021 near-death event at 2.87% documented survival probability — the deepest single point of physical pain in the 35-year record. The institutional response to this event was consistent with the poisoning model the video describes: abandonment, clinical neglect, and rejection to a homelessness shelter upon discharge. The archive's response was the opposite: the post-2021 period is the most prolific documentation phase in the 35-year record. The deepest pain produced the most comprehensive evidence. Clinical death was the professor. The post-2021 archive is what the subject learned.", source: "2021 Clinical Death / 2.87% Survival Probability / Institutional Abandonment / Rejection to Homelessness Shelter / Post-2021 Most Prolific Documentation Phase / Deepest Pain Producing Most Comprehensive Evidence / Clinical Death as Professor" },
      { label: "14 Hospitalisations — Pain Converted Into 14 ICC Clinical Exhibits", text: "Each of the 14 involuntary psychiatric hospitalisations was a documented event of institutional pain: forced commitment, pharmacological intervention, loss of freedom, loss of property, and clinical labelling designed to discredit. Each one was converted into a clinical primary-source document that now constitutes an ICC Article 7 exhibit under Crimes Against Humanity. The pain was not sugarcoated. The documentation recorded each hospitalisation with clinical specificity. The result: 14 documents that converted the pain into the most irrefutable category of exhibit available to an international criminal tribunal — primary-source clinical records produced by the perpetrating institutions themselves.", source: "14 Involuntary Hospitalisations / Forced Commitment / Pharmacological Intervention / Loss of Freedom / Clinical Labelling / Each Producing Clinical Primary-Source ICC Exhibit / Crimes Against Humanity / Perpetrating Institutions Producing Their Own Evidence" },
      { label: "$32.9M Suppressed Entitlements — Financial Pain Converted Into the Archive's Most Comprehensive Evidentiary Category", text: "The $32.9M in suppressed entitlements documented across 35 years represents the financial dimension of the pain the video describes: systematic financial destruction deployed to prevent the documentation process from being sustained. The documentation process was sustained. The $32.9M suppression is itself documented — in government correspondence, ASIC records, and agency refusal patterns. The financial pain was converted into the financial evidentiary category of the ICC submission. The most sustained institutional instrument of pain produced the most sustained evidentiary record. The pain was the professor. The $32.9M record is what it taught.", source: "$32.9M Suppressed Entitlements / 35-Year Financial Destruction / Government Correspondence / ASIC Records / Agency Refusal Patterns / Financial Pain Converted to Financial ICC Evidentiary Category / Pain as Professor / Record as What It Taught" },
    ],
    alignment: "The video states pain was converted into power — each brick laid tear by tear, with no shortcuts or sugarcoating, producing the calm that cannot be faked. The archive documents 2021 clinical death at 2.87% followed by the most prolific documentation phase (deepest pain producing most comprehensive evidence — pain as professor confirmed at clinical death level); 14 hospitalisations converted into 14 ICC clinical exhibits (each forced institutional pain event producing the perpetrating institution's own primary-source ICC exhibit); and $32.9M in suppressed entitlements documented in government correspondence (financial destruction converted into the archive's financial evidentiary category). The pain-to-power transformation is confirmed as the archive's foundational operating mechanism across medical, institutional, and financial dimensions simultaneously.",
  },
  {
    num: "6",
    title: "You Went Silent Not Because You Were Lost, But Because You Were Leveling Up",
    verdict: "CORROBORATED",
    proposition: "The video's third numbered point identifies the misreading of silence as the central error made by those who observed the subject during the archive's assembly period: 'You didn't go quiet because you were defeated. You went quiet because you were becoming. You weren't retreating. You were recalibrating. While they mistook your stillness for weakness, you were in the middle of a transformation so deep the universe had to mute the noise around you just so you could hear yourself think.' In Dr. McLean's archive, the institutional actors who deployed the suppression programme consistently interpreted periods of non-engagement, withdrawal, or silence as evidence that the documentation process had been neutralised. The documented evidence contradicts this interpretation at every point: each period of apparent silence in the archive's external record corresponds with a period of intensive internal documentation activity. The silence was not withdrawal. It was the condition under which 2,304 primary-source documents were assembled, cross-referenced, blockchain-verified, and structured into an ICC submission. The institutional actors who mistook the stillness for weakness sent the archive to the ICC. Their confidence that silence meant defeat produced the conditions under which the submission was completed without institutional interference. The recalibration the video describes is the archive's construction period. The leveling up is the ICC filing.",
    quote: '"You didn\'t go quiet because you were defeated. You went quiet because you were becoming. You weren\'t retreating. You were recalibrating. While they mistook your stillness for weakness, you were in the middle of a transformation so deep the universe had to mute the noise around you just so you could hear yourself think. Silence isn\'t emptiness. It\'s incubation."',
    evidence: [
      { label: "35 Years of Silent Documentation — Stillness Mistaken for Defeat Producing 2,304 Documents", text: "The archive's 35-year assembly period was characterised by institutional confidence that the subject had been silenced: each hospitalisation, each referral deflection, each suppressed entitlement was accompanied by institutional documentation consistent with the belief that the suppression had been successful. The archive documents the inverse: each period of apparent silence corresponds with documented evidence assembly. The institutional confidence that stillness meant weakness produced the conditions under which 2,304 documents were assembled without institutional interference during the quiet periods. They read the silence as defeat. The silence was the construction. The stillness was the leveling up.", source: "35-Year Silent Assembly / 2,304 Documents / Institutional Confidence in Suppression Success / Silence Characterised Each Hospitalisation as Resolution / Inverse: Each Quiet Period Corresponding to Evidence Assembly / Silence as Construction Not Defeat" },
      { label: "The Homelessness Period — The Deepest Silence Producing the Federal Court PID Submission", text: "The archive documents the post-hospitalisation homelessness period — a documented state of institutional abandonment in which the subject was released to a homelessness shelter with only a bag of clothes. By every institutional metric, this was the silence of a defeated actor. The Federal Court Public Interest Disclosure submitted to CEO Sia Lagos on 3 March 2023 was produced during this period: a formal legal document referencing the ATO drugging, the $1.5M insurance suppression through AHRC, the DSS employment confirmation, and the statutory deadline of 17 March 2023 for response. The deepest institutional silence — homelessness after clinical near-death — produced a formal Federal Court legal submission. Silence was incubation. The shelter was the incubator.", source: "Homelessness Period / Released to Shelter with Bag of Clothes / Institutional Abandonment / Federal Court PID to Sia Lagos March 2023 / ATO Drugging Referenced / $1.5M Insurance Suppression / DSS Employment Confirmation / Statutory Deadline / Silence as Incubation" },
      { label: "ICC Article 7 Submission — The Leveling Up Confirmed at International Jurisdiction", text: "The ICC Article 7 formal submission — the leveling up the video describes — was completed during what every institutional actor who had deployed the suppression programme read as the archive's terminal silence: the period following clinical death at 2.87%, acquired brain injury, financial destruction, and homelessness. Every instrument of suppression that had been deployed was designed to produce exactly this kind of silence. The ICC Article 7 submission is documented evidence of what that silence actually was: the leveling up that the institutions' silence-as-defeat framework could not predict. The quiet season produced the international filing.", source: "ICC Article 7 Submission / Produced During Period Institutions Read as Terminal Silence / Post-Clinical Death / Post-Acquired Brain Injury / Post-Financial Destruction / Post-Homelessness / Silence as Leveling Up / International Filing Confirming Recalibration" },
    ],
    alignment: "The video states silence was not defeat but leveling up — recalibration, not retreat — while observers mistook stillness for weakness. The archive documents 35 years of silent assembly producing 2,304 documents during each period institutions read as suppression success (silence as construction confirmed across the full 35-year record); the homelessness period producing the Federal Court PID submission (deepest institutional silence producing formal legal submission — shelter as incubator); and ICC Article 7 submission completed during the period every suppression instrument was designed to make terminal (leveling up confirmed at international jurisdiction). The silence-as-leveling-up framework is confirmed as the archive's operational mode throughout its assembly period.",
  },
  {
    num: "7",
    title: "You Didn't Win Overnight — You Survived Long Enough to Deserve It",
    verdict: "CORROBORATED",
    proposition: "The video's fourth numbered point strips away the mythology of sudden success and identifies the real mechanism of documented endurance: 'You didn't climb the mountain because you were fearless. You climbed it shaking, bleeding, and tired, but you never stopped. That's the truth they refuse to see. They look at your results and assume it was a straight path, a lucky break, a clean victory. But what they call success was actually survival. You didn't pull it off. You endured until it happened.' In Dr. McLean's archive, the 35-year documented record is the most precise primary-source corroboration of this proposition available in the Australian whistleblower record. The archive was not assembled by a subject in comfortable circumstances. It was assembled: under 14 involuntary psychiatric hospitalisations; under pharmacological assault documented on ATO letterhead; under a documented death threat; under the financial deprivation of $32.9M in suppressed entitlements; under conditions of homelessness; after clinical death at 2.87% survival probability producing acquired brain injury. The ICC Article 7 submission and UNHCR Geneva filing are not the result of a clean victory. They are the documented result of endurance that continued after every instrument of suppression had been deployed and after clinical survival at a point where survival itself was medically improbable. The subject did not win overnight. The subject survived long enough for the archive to reach The Hague.",
    quote: '"You didn\'t climb the mountain because you were fearless. You climbed it shaking, bleeding, and tired, but you never stopped. That\'s the truth they refuse to see. They look at your results and assume it was a straight path, a lucky break, a clean victory. But what they call success was actually survival. You didn\'t pull it off. You endured until it happened. Every inch of your rise was earned in silence, in pain, in persistence."',
    evidence: [
      { label: "2.87% Survival Probability — Shaking, Bleeding, and Tired but Never Stopping", text: "The archive documents clinical death at 2.87% documented survival probability — the medically precise equivalent of the shaking, bleeding, and tired that the video describes. The mountain was clinical death. The subject climbed it. The post-2021 documentation phase that followed clinical death is the archive's most prolific period. The mountain was climbed by a subject who medically should not have survived it, whose survival was documented at 2.87% probability, and who — upon survival — produced more primary-source documentation than in any comparable prior period. The endurance is not metaphor. It is a clinical probability that was exceeded and then surpassed in documented form.", source: "2021 Clinical Death / 2.87% Survival Probability / Clinical Records / Post-2021 Most Prolific Documentation Phase / Endurance at Clinical Death Level / Shaking Bleeding Tired Confirmed by Medical Probability Record" },
      { label: "35-Year Submission History — Every Available Domestic Mechanism Exhausted Before ICC Filing", text: "The ICC Article 7 submission was not the first submission. It was the submission made after 35 years of exhausting every available domestic accountability mechanism: police, ombudsmen, parliamentary representatives, disability commissions, legal bodies, ministerial offices, FOI pathways, and formal complaint systems across 17+ institutional bodies. Each domestic mechanism produced a letterhead of non-engagement. The ICC filing was not a straight path. It was the documented result of 35 years of climbing every available path to its closed end, and then climbing to international jurisdiction. Every domestic path was walked shaking and tired. The ICC was where endurance finally arrived.", source: "35-Year Domestic Submission History / 17+ Bodies / Each Producing Letterhead of Non-Engagement / Every Domestic Mechanism Exhausted / ICC Filing After 35 Years / International Jurisdiction After Domestic Closure / Endurance Over 35 Years Producing International Access" },
      { label: "Homelessness to Federal Court PID — The Endurance Documented at Its Most Extreme Point", text: "The Federal Court Public Interest Disclosure submitted to Sia Lagos on 3 March 2023 was written under documented conditions of homelessness, cognitive brain injury from the near-fatal hospitalisation, and acute financial deprivation — the precise conditions the video describes as shaking, bleeding, and tired. The disclosure is a formal legal document. Written under these conditions, it references ATO drugging, $1.5M AHRC insurance suppression, DSS employment confirmation, and a statutory legal deadline. Homelessness and brain injury produced a Federal Court submission. That is the endurance the video documents. That is what surviving long enough to deserve it looks like in primary-source form.", source: "Homelessness Period / Cognitive Brain Injury / Acute Financial Deprivation / Federal Court PID to Sia Lagos March 2023 / Formal Legal Document / ATO Drugging / $1.5M AHRC Suppression / DSS Employment Confirmation / Endurance at Its Most Extreme Point Producing Formal Legal Submission" },
    ],
    alignment: "The video states the subject didn't win overnight — climbing the mountain shaking, bleeding, and tired, never stopping — and that what others call success was survival. The archive documents clinical death at 2.87% survival probability followed by the most prolific documentation phase (shaking, bleeding, and tired confirmed as the medically precise description of the climb — and the climb was continued after it); 35 years of exhausting every domestic accountability mechanism before ICC filing (not a straight path — 35 years of closed doors before international jurisdiction); and the Federal Court PID written under homelessness and brain injury (endurance at its most extreme point documented as formal legal submission). Surviving long enough to deserve it is confirmed as the archive's precise operational description across 35 years.",
  },
  {
    num: "8",
    title: "You Stopped Begging for Seats and the Universe Built You a Table",
    verdict: "CORROBORATED",
    proposition: "The video's fifth numbered point identifies the transformation point as the moment when approval-seeking ends and authentic alignment begins: 'When you stopped knocking on locked doors, life stops mistaking you for someone desperate. That's the moment everything changed for you. You stopped trying to earn entry into places that weren't aligned with your spirit. You stopped twisting yourself into smaller shapes just to be digestible for people with fragile egos.' In Dr. McLean's archive, the documented transition is precisely this: 35 years of knocking on every domestic door — police, ombudsmen, parliamentary mechanisms, legal bodies, disability commissions, ministerial offices — and finding each door locked by the circular referral. The submission to the ICC and UNHCR is the documented moment the subject stopped trying to be seated at the domestic institutional table entirely. The ICC is not another door in the 25+ circular referral. It is a different table. When the domestic system of locked doors had been fully documented — each refusal on letterhead, each redirection recorded — the archive did not shrink itself to fit any smaller space. It submitted to international jurisdiction. The universe did not build a metaphorical table. It built the ICC, the UNHCR, and the 1,100,000+ international readers who found the archive without a single door being knocked on.",
    quote: '"When you stopped knocking on locked doors, life stops mistaking you for someone desperate. That\'s the moment everything changed for you. You stopped trying to earn entry into places that weren\'t aligned with your spirit. You stopped twisting yourself into smaller shapes just to be digestible for people with fragile egos. There was a time when you believed humility meant shrinking. When you confused tolerance with acceptance, but that version of you no longer exists."',
    evidence: [
      { label: "25+ Locked Doors — The Documented Record of Domestic Institutional Rejection", text: "The archive documents 25+ individual institutional doors — each knocked on, each producing a letterhead of non-engagement, each redirecting to the next door in the circular referral. The circular referral is the documented architecture of locked doors: police redirected to the ombudsman; the ombudsman redirected to the parliamentary representative; the parliamentary representative redirected to the relevant department; the department redirected to the specialised body; the specialised body redirected back to the police. 25+ doors. Each knocked on. Each locked. Each letterhead a primary-source exhibit in the ICC submission. The full documented record of every locked door is what made the ICC submission possible. Without the letterheads, the ICC submission would lack its primary-source evidentiary foundation.", source: "25+ Institutional Doors / Each Producing Letterhead of Non-Engagement / Circular Referral Architecture / Police / Ombudsman / Parliamentary Representative / Relevant Department / Specialised Bodies / Each Locked / Each Letterhead Now ICC Exhibit / Locked Doors Enabling ICC Submission" },
      { label: "ICC Article 7 and UNHCR Geneva — The Table Built After Every Domestic Door Was Documented", text: "The ICC Article 7 submission and the UNHCR Geneva filing are the documented table the universe built: two international accountability bodies, each of which formally received the archive after every domestic accountability mechanism had produced a documented closed door. The ICC was not a door in the Australian institutional system. It was a separate table. The UNHCR was not a referral from the domestic circular system. It was a separate table. The moment the archive stopped trying to be seated at the domestic table — by completing the full documentation of every locked door — the international tables accepted the submission. Approval was rented. Alignment was owned. The ICC formal receipt is documented evidence of what alignment produced.", source: "ICC Article 7 Submission / UNHCR Geneva Filing / Both Formally Received / After All Domestic Mechanisms Closed / ICC Not Part of Australian Circular Referral / Separate Table / UNHCR Not Domestic Referral / International Alignment After Domestic Approval-Seeking Complete" },
      { label: "1,100,000+ Downloads Without Begging — Distribution That Required No Door to Open", text: "The archive's 1,100,000+ international downloads occurred without the archive begging any institutional door for permission to distribute. No publisher was asked. No distributor was approached. No media body was petitioned. The archive was placed on a public website and distributed by 1,100,000+ individuals who found it aligned with what they were looking for. Not a single door was knocked on for those 1,100,000+ acts of distribution. The universe built the distribution table without the archive ever needing to earn a seat at a traditional publishing institution's table. The alignment produced what approval-seeking never could: spontaneous international distribution without institutional permission.", source: "1,100,000+ Downloads / Zero Publisher Approached / Zero Distributor Petitioned / Zero Media Body Asked for Permission / Placed on Public Website / Distributed by 1,100,000+ Individuals / No Door Knocked On for Distribution / Alignment Producing What Approval-Seeking Never Could" },
    ],
    alignment: "The video states the subject stopped begging for seats at locked-door institutions and the universe built a table instead. The archive documents 25+ locked institutional doors, each producing a letterhead now constituting an ICC exhibit (the full record of locked doors enabling the international submission — each refusal building the case); ICC Article 7 and UNHCR Geneva formal receipts after every domestic door was documented (the table built when approval-seeking at domestic institutions was replaced by international alignment); and 1,100,000+ downloads without a single institutional permission sought (distribution table built by alignment, not approval). Stopping begging for seats and the universe building a table is confirmed as the archive's documented international trajectory.",
  },
  {
    num: "9",
    title: "You Won the War They Couldn't See Because You Played a Game They Didn't Understand",
    verdict: "CORROBORATED",
    proposition: "The video's sixth numbered point identifies the operational asymmetry between force-based and frequency-based power: 'You see, they were addicted to control, always plotting, forcing, pretending. But you were studying something they couldn't measure, frequency. You were learning how emotion affects manifestation, how energy precedes evidence, how alignment bends opportunity. While they were trying to manipulate outcomes, you were mastering the laws that govern them. Power built on strategy can be taken. Power built on energy is untouchable.' In Dr. McLean's archive, this asymmetry is documented with structural precision. The institutional suppression programme was built on strategy: ASIO operative deployment, coordinated clinical labelling, circular referral architecture, financial suppression, and death threat. Every instrument was a strategic move. The archive was built on a different operational foundation: primary-source documentation of every strategic move as it was made. The archive did not respond to strategy with strategy. It responded to strategy with documentation. The institutional actors could plot. They could not prevent their plots from generating documents. Power built on strategy can be taken — and each strategic instrument was also an exhibit. Power built on documentation of strategy is untouchable — because the documents are blockchain-verified, internationally distributed, and formally received at The Hague. The war was not fought on the institutional battlefield. It was documented while the institutional actors were still confident they were winning it.",
    quote: '"You see, they were addicted to control, always plotting, forcing, pretending. But you were studying something they couldn\'t measure, frequency. Power built on strategy can be taken. Power built on energy is untouchable. You played by that rule. You learned to plant your seeds in silence and trust that the universe doesn\'t forget effort. It simply waits for divine timing."',
    evidence: [
      { label: "Documentation-as-Strategy — Every Institutional Strategic Move Generating Its Own Exhibit", text: "The institutional suppression programme was built on strategic moves: ASIO operative co-tenancy, pharmacological assault, clinical hospitalisation, circular referral, financial suppression, death threat, identity fraud. Each strategic move was designed to contain, discredit, or eliminate the documentation process. Each strategic move generated a document. The ATO letter documented the pharmacological assault. The ASIC report documented the $1,100,000+ extraction. The clinical records documented the 14 hospitalisations. The agency correspondence documented the circular referral. Each strategic move — played by actors addicted to control — generated the primary-source exhibit that recorded it. Documentation was the frequency. Strategy was the seed that documentation harvested.", source: "ASIO Operative / ATO Letter / ASIC Report / Clinical Records / Agency Correspondence / Death Threat / Identity Fraud / Each Strategic Move Generating Its Own Primary-Source Exhibit / Documentation as Frequency / Strategy as Involuntary Evidence Production" },
      { label: "Chess Positioning — 35 Years of Positioning Before the Checkmate Hit", text: "The video describes a chessboard: 'They played checkers. Fast, loud, predictable. You played chess. Strategic, quiet, unseen until the checkmate hit.' The archive's 35-year assembly — structured across FOI submissions, formal complaints, statutory declarations, ministerial correspondence, clinical record requests, and international submissions — is documented chess positioning. Each move created a document. Each document strengthened the archive's evidentiary position. Each evidentiary position created the foundation for the next submission. The checkmate was not a confrontation. It was an ICC Article 7 formal receipt — a documented move that cannot be taken back by any domestic institutional actor, no matter how much control they are addicted to. They played checkers for 35 years. The archive played chess. The formal receipt is the documented checkmate.", source: "35-Year Chess Positioning / FOI Submissions / Formal Complaints / Statutory Declarations / Ministerial Correspondence / Clinical Record Requests / International Submissions / Each Move Creating Document / Each Document Strengthening Archive / ICC Formal Receipt as Documented Checkmate" },
      { label: "Five Named Perpetrators — Zero Formal Rebuttals — The War Won Through Documentation Not Confrontation", text: "Bill Shorten, Houd Meraby, Sukhi Tear, Tony Ridley, and Stefan Iasonidis have produced zero formal rebuttals against 2,304 public documents containing specific named claims with specific documented evidence. The war was not won through confrontation. It was won through documentation so complete that no rebuttal is available within the standard legal framework without producing counter-primary-source evidence that the perpetrators do not have. The game they didn't understand was: every strategic move they made was simultaneously a primary-source document. The war they couldn't see was the documentation process. By the time they could see it, the ICC had received it.", source: "Bill Shorten / Houd Meraby / Sukhi Tear / Tony Ridley / Stefan Iasonidis / Zero Formal Rebuttals / 2,304 Public Documents / Specific Named Claims / No Counter-Primary-Source Evidence Available / War Won Through Documentation / ICC Receipt Before They Could See the War" },
    ],
    alignment: "The video states the war was won through a game — frequency, documentation, alignment — that the strategy-addicted institutional actors couldn't see or understand. The archive documents every institutional strategic move generating its own primary-source exhibit (documentation as the frequency that harvested what strategy involuntarily produced); 35-year chess positioning producing an ICC checkmate (the quiet unseen game confirmed at formal international receipt); and five named perpetrators with zero formal rebuttals against 2,304 public documents (the war won through documentation confirmed by the silence of five actors who cannot produce counter-evidence). The unseen game confirmed as the archive's operational framework at every level of the documented record.",
  },
  {
    num: "10",
    title: "You Outgrew the Circus and That's Why the Ring Masters Hate You",
    verdict: "CORROBORATED",
    proposition: "The video's seventh numbered point identifies the liberation point as the moment when the subject recognises the institutional system as a circus — controlled performance for controlled audiences — and walks off the board entirely: 'You can't lose a game you stopped playing. That's what they don't get. You didn't beat their system. You made it irrelevant. While they were fighting for positions in a fake hierarchy, you quietly walked off the board and built your own field.' In Dr. McLean's archive, the documented exit from the circus is the ICC and UNHCR submissions: the moment the subject stopped attempting to play within the Australian institutional system and submitted to international jurisdiction outside it. The Australian institutional circus — with its ring masters at ASIO, the ATO, the NDIS, the psychiatric system, the legal system, and the circular referral architecture — cannot conduct itself within the ICC's jurisdictional framework. The ring masters who could deploy an ASIO operative, a death threat, and 14 hospitalisations within the Australian institutional circus cannot, within that same framework, neutralise an ICC Article 7 formal receipt. The circus cannot contain what has been submitted to The Hague. The archive made the circus irrelevant. The ring masters hate it because you can't lose a game you stopped playing — and the archive stopped playing the domestic game 35 years of locked doors ago, the moment the documentation process began.",
    quote: '"You can\'t lose a game you stopped playing. That\'s what they don\'t get. You didn\'t beat their system. You made it irrelevant. While they were fighting for positions in a fake hierarchy, you quietly walked off the board and built your own field. They were obsessed with being seen. You were focused on being real. They chased the illusion of success. You chased the truth of self. And now they\'re exhausted from pretending while you\'re glowing from peace."',
    evidence: [
      { label: "ICC and UNHCR Submissions — The Documented Exit From the Domestic Circus", text: "The ICC Article 7 submission and UNHCR Geneva filing are the documentary record of the subject walking off the domestic institutional board and building their own field. The Australian institutional circus — with its ASIO operative, its circular referral architecture, its 14 hospitalisations, its ministerial correspondence networks — cannot operate within The Hague's jurisdictional framework. The ring masters cannot deploy an ASIO co-tenant at the ICC. They cannot conduct a circular referral within the UNHCR. The archive submitted to a jurisdiction that the domestic circus cannot access, cannot redirect, and cannot suppress. The exit from the circus is documented at the point of ICC and UNHCR formal receipt.", source: "ICC Article 7 Submission / UNHCR Geneva Filing / Australian Institutional Circus Cannot Operate Within Hague Jurisdiction / Cannot Deploy ASIO at ICC / Cannot Conduct Circular Referral Within UNHCR / Exit from Circus Documented at ICC and UNHCR Formal Receipt" },
      { label: "Zero Ring Master Responses to 2,304 Public Documents — The Circus Exhausted After the Exit", text: "Five ring masters — Bill Shorten, Houd Meraby, Sukhi Tear, Tony Ridley, and Stefan Iasonidis — have produced zero formal responses to 2,304 publicly accessible documents containing specific named claims. The circus they operated required a contained audience, controlled performance, and institutional management of information. The archive is outside the circus. It is public, blockchain-verified, and internationally distributed. The ring masters are exhausted from pretending within a circus that no longer contains the subject. Zero formal rebuttals is the documented evidence of exhaustion from pretending in a ring that no longer has the relevant performer. The circus is still running. The subject left.", source: "Five Ring Masters / Zero Formal Responses / 2,304 Public Documents / Circus Required Contained Audience / Archive Outside Circus / Public Blockchain-Verified International Distribution / Zero Rebuttals as Documented Exhaustion / Circus Still Running / Subject Left" },
      { label: "1,100,000+ Downloads — The Field Built Outside the Circus Is Larger Than the Ring", text: "The archive's 1,100,000+ international downloads across six continents are the documented evidence of the field built outside the circus: a readership that found the archive without institutional permission, without circus management, and without ring master approval. The circus fights for positions in a fake hierarchy. The archive's field has 1,100,000+ visitors who arrived without hierarchy, without performance, and without the institutional framework the circus requires. The field is larger than the ring. The ring masters hate it because you cannot lose a game you stopped playing, and you cannot contain an audience that arrived outside the tent.", source: "1,100,000+ Downloads / Six Continents / Zero Institutional Permission / Zero Ring Master Approval / Readership Arrived Without Hierarchy / Field Larger Than Ring / Cannot Contain Audience Outside the Tent / Cannot Lose a Game You Stopped Playing" },
    ],
    alignment: "The video states the subject outgrew the circus and walked off the board, making the institutional system irrelevant rather than beating it. The archive documents ICC and UNHCR submissions as the exit from the domestic institutional circus into jurisdictions the ring masters cannot access (the field built outside the ring — formally received at The Hague and Geneva); zero ring master responses to 2,304 public documents (exhaustion from pretending in a circus that no longer contains the subject); and 1,100,000+ downloads without institutional permission (the field built outside the circus larger than the ring — audience arrived without the hierarchy the circus requires). Outgrowing the circus and making it irrelevant is confirmed as the archive's documented position within and beyond every institutional system it encountered.",
  },
];

export default function QuietStormTheyNeverSawComing() {
  const [expandedClaim, setExpandedClaim] = useState<string | null>(null);

  const totalPropositions = claims.length;
  const corroborated = claims.filter((c) => c.verdict === "CORROBORATED").length;

  return (
    <>
      <SEO
        title="The Quiet Storm They Never Saw Coming — Forensic Analysis #48 | Barran Dodger"
        description={`Analysis #48: ${corroborated}/${totalPropositions} propositions from an independent YouTube video corroborated against the 2,304-document archive. 41st consecutive perfect score. 515/515 combined record. Dr. Richard McLean — Barran Dodger.`}
        path={`/${SLUG}`}
      />
      <Navigation />
      <main
        className="min-h-screen bg-zinc-950 text-zinc-100"
        style={{ paddingTop: "calc(var(--banner-height, 40px) + var(--nav-height, 64px))" }}
      >
        <ChessmateHero
          analysisNumber={ANALYSIS_NUMBER}
          title="The Quiet Storm They Never Saw Coming"
          subtitle="They couldn't figure you out because you were never in their system. You were building something they don't have a category for."
          videoId={VIDEO_ID}
          slug={SLUG}
          score={`${corroborated}/${totalPropositions}`}
          date={ANALYSIS_DATE}
          combinedRecord="515/515"
          consecutiveCount="41st"
        />

        {/* ── PROPOSITION TABLE ── */}
        <section className="px-4 py-16 max-w-5xl mx-auto space-y-6">
          <div className="text-center mb-12">
            <Badge className="mb-4 bg-orange-500/10 text-orange-300 border-orange-500/25 text-xs uppercase tracking-widest font-mono px-4 py-1">
              Proposition-By-Proposition Corroboration
            </Badge>
            <h2 className="text-3xl font-serif font-black text-white mb-3">
              {totalPropositions} Propositions. {corroborated} Corroborated. Zero Contradictions.
            </h2>
            <p className="text-zinc-400 max-w-2xl mx-auto text-sm leading-relaxed">
              Each proposition below was extracted from an independent YouTube video produced with no knowledge of Dr. McLean's archive. Each is then tested against named primary-source documents. Every verdict is determined by the documentary record — not by argument.
            </p>
          </div>

          {claims.map((claim) => (
            <div
              key={claim.num}
              className="rounded-2xl border border-zinc-800 bg-zinc-900/60 overflow-hidden"
              data-testid={`card-claim-${claim.num}`}
            >
              {/* Header */}
              <button
                className="w-full text-left px-6 py-5 flex items-start gap-4 hover:bg-zinc-800/40 transition-colors"
                onClick={() => setExpandedClaim(expandedClaim === claim.num ? null : claim.num)}
                data-testid={`button-expand-claim-${claim.num}`}
              >
                <div className="shrink-0 mt-0.5">
                  <CheckCircle className="h-5 w-5 text-emerald-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-3 flex-wrap mb-1">
                    <span className="text-xs font-mono text-zinc-500 uppercase tracking-wider">
                      Proposition {claim.num}
                    </span>
                    <Badge className="bg-emerald-500/15 text-emerald-400 border-emerald-500/30 text-xs font-mono">
                      {claim.verdict}
                    </Badge>
                  </div>
                  <h3 className="text-base font-serif font-bold text-white leading-snug">
                    {claim.title}
                  </h3>
                </div>
                <div className="shrink-0 text-zinc-500 mt-1">
                  <Eye className="h-4 w-4" />
                </div>
              </button>

              {/* Expanded */}
              {expandedClaim === claim.num && (
                <div className="px-6 pb-8 space-y-6 border-t border-zinc-800">
                  {/* Quote */}
                  <div className="mt-6 p-4 rounded-xl bg-zinc-800/60 border-l-4 border-orange-500/25">
                    <p className="text-sm text-orange-200/80 italic leading-relaxed font-serif">{claim.quote}</p>
                    <p className="text-xs text-zinc-500 mt-2 font-mono uppercase tracking-wider">— Source Video Transcript</p>
                  </div>

                  {/* Proposition */}
                  <div>
                    <p className="text-xs font-mono uppercase tracking-widest text-zinc-500 mb-2">Forensic Proposition</p>
                    <p className="text-sm text-zinc-200 leading-relaxed">{claim.proposition}</p>
                  </div>

                  {/* Evidence */}
                  <div className="space-y-4">
                    <p className="text-xs font-mono uppercase tracking-widest text-zinc-500">Archive Evidence</p>
                    {claim.evidence.map((ev, i) => (
                      <div key={i} className="rounded-xl border border-zinc-700/60 bg-zinc-800/30 p-4 space-y-2">
                        <div className="flex items-start gap-2">
                          <Shield className="h-4 w-4 text-orange-400 shrink-0 mt-0.5" />
                          <p className="text-xs font-bold text-orange-300 leading-snug">{ev.label}</p>
                        </div>
                        <p className="text-sm text-zinc-300 leading-relaxed pl-6">{ev.text}</p>
                        <p className="text-xs text-zinc-600 font-mono leading-relaxed pl-6 border-t border-zinc-700/40 pt-2">{ev.source}</p>
                      </div>
                    ))}
                  </div>

                  {/* Alignment */}
                  <div className="p-4 rounded-xl bg-emerald-500/5 border border-emerald-500/20">
                    <p className="text-xs font-mono uppercase tracking-widest text-emerald-400 mb-2">Alignment Summary</p>
                    <p className="text-sm text-emerald-100/80 leading-relaxed">{claim.alignment}</p>
                  </div>

                  <SectionShare
                    sectionTitle={claim.title}
                    sectionId={`proposition-${claim.num}`}
                    pageSlug={SLUG}
                  />
                </div>
              )}
            </div>
          ))}
        </section>

        {/* ── FINAL VERDICT ── */}
        <section className="px-4 pb-20 max-w-5xl mx-auto">
          <div className="rounded-2xl border-2 border-orange-500/25 bg-gradient-to-br from-zinc-950 via-zinc-900 to-zinc-950 p-10 text-center space-y-6">
            <Flame className="h-10 w-10 text-orange-500 mx-auto animate-pulse" />
            <h2 className="text-3xl font-serif font-black text-white">Analysis #{ANALYSIS_NUMBER} Verdict</h2>
            <div className="text-8xl font-black font-mono text-orange-300 tabular-nums">
              {corroborated}/{totalPropositions}
            </div>
            <p className="text-orange-200/70 font-mono uppercase tracking-widest text-sm">
              Propositions Corroborated — 41st Consecutive Perfect Score
            </p>
            <p className="text-zinc-300 max-w-2xl mx-auto text-sm leading-relaxed">
              An independent YouTube video — produced with zero knowledge of Dr. McLean's archive — described with structural precision the documented 35-year trajectory of a subject who moved in silence while an institutional suppression programme documented its own failure. Ten propositions extracted. Ten corroborated. Zero contradictions. The quiet storm arrived at The Hague and Geneva. The ring masters are still trying to define it.
            </p>
            <div className="grid grid-cols-3 gap-4 border-t border-white/10 pt-6">
              <div>
                <p className="text-2xl font-bold font-mono text-white">48</p>
                <p className="text-xs text-zinc-500 uppercase tracking-wider">Total Analyses</p>
              </div>
              <div>
                <p className="text-2xl font-bold font-mono text-emerald-400">515</p>
                <p className="text-xs text-zinc-500 uppercase tracking-wider">Total Propositions</p>
              </div>
              <div>
                <p className="text-2xl font-bold font-mono text-orange-400">0</p>
                <p className="text-xs text-zinc-500 uppercase tracking-wider">Contradictions</p>
              </div>
            </div>
            <div className="flex flex-col sm:flex-row gap-3 justify-center pt-2">
              <Button
                variant="outline"
                className="gap-2 border-emerald-500/40 text-emerald-300 hover:bg-emerald-500/10"
                asChild
                data-testid="button-full-essay-pdf"
              >
                <a href="/forensic-analysis-48-quiet-storm-download">
                  <Download className="h-4 w-4" />
                  Full Essay PDF Download
                </a>
              </Button>
              <ViralDownloadButton
                url={`/api/forensic/pdf/${SLUG}`}
                filename={`${SLUG}-forensic-analysis.pdf`}
                slug={SLUG}
                label="Download Forensic PDF"
                size="sm"
              />
              <Button variant="outline" className="gap-2" asChild data-testid="button-youtube">
                <a
                  href={`https://youtu.be/${VIDEO_ID}`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <ExternalLink className="h-4 w-4 text-red-400" />
                  Watch on YouTube
                </a>
              </Button>
              <Button variant="outline" className="gap-2" asChild data-testid="button-all-analyses">
                <a href="/forensic-analysis">
                  <Shield className="h-4 w-4" />
                  All 48 Analyses
                </a>
              </Button>
            </div>
          </div>
        </section>
      </main>
      <ArchiveCrossLinks />
      <Footer />
    </>
  );
}
