import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { CheckCircle, Download, ExternalLink, Eye, Scale, Shield, BookOpen, AlertTriangle, Users, Gavel, Search, Mic } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import { SEO } from "@/components/SEO";
import { ArchiveCrossLinks } from "@/components/ArchiveCrossLinks";
import { ViralDownloadButton } from "@/components/ViralDownloadButton";
import coverImg from "@/assets/images/cover-wait-theyre-listening-forensic.png";

const SLUG = "wait-theyre-listening-forensic";
const VIDEO_ID = "d2QOKHyZf5I";
const ANALYSIS_DATE = "23 April 2026";
const ANALYSIS_NUMBER = "32";
const VIDEO_TITLE = "WAIT... THEY'RE LISTENING";
const DOC_FILE = "wait-theyre-listening-forensic-examination.pdf";

const PROPOSITIONS = [
  {
    num: "P·01",
    timestamp: "00:00:14",
    part: "Part 1 — The Confession",
    title: '"Someone finally broke the silence. Someone cracked under the pressure of their own guilt. Someone from that circle confessed everything they did behind it. And I mean everything. Spilled like poison from a cup they can\'t put back together."',
    verdict: "CORROBORATED",
    corroboration: "DIRECT — The Archive IS the Confession",
    proposition: "The video's central premise is a confession — someone from inside the suppression circle disclosed, in documented detail, everything that was done. In Dr. McLean's case, the 'confessor' is not a single person. It is the archive itself: 2,304 primary-source documents that collectively constitute the most comprehensive documented confession of coordinated institutional persecution in the Australian whistleblower record. The ATO letter confirming drugging, the ASIC Report documenting the $1,100,000+ extraction, the Statutory Declaration confirming ASIO operative status, the Intervention Order L12151974, the MHRT Variation Order signed by Michael Crompton — each is a document generated from within the suppression network that disclosed, in the language of administration, what the network did. The cup was not put back together. The documents exist.",
    quote: '"They thought their secret pacts were unbreakable, that their whispered conversations would stay buried in the archives of their cowardice."',
    evidence: [
      { label: "ATO Letter — Drugging Confirmed in Government Language", text: "The Australian Taxation Office letter in the archive confirms, in bureaucratic language, that Dr. McLean was drugged. This is a document generated by a government institution that functioned, involuntarily, as a confessor — disclosing in official correspondence what the suppression network did. The cup cannot be put back together. The letter exists.", source: "Silent Assassin Analysis #28 — ATO letter reference / barrandodger.com/silent-assassin" },
      { label: "ASIC Report — $1,100,000+ Extraction Documented", text: "The Australian Securities and Investments Commission report documents a $1,100,000+ extraction connected to Iasonidis's operation. This is not an allegation. It is a regulatory body's documentation of financial misconduct — another institutional confessor that disclosed, in official report language, what was done.", source: "ASIC Report — Archive Evidence Register" },
      { label: "2,304 Primary-Source Documents — The Complete Confession", text: "The archive contains 2,304 primary-source documents. Each one is a fragment of the confession the video describes: government letterhead, court records, statutory declarations, compliance notices, ATO correspondence, ASIC reports, MHRT orders. Collectively they constitute a detailed, cross-referenced, blockchain-verified account of what the suppression circle did. The secret pacts they believed were unbreakable are now public record.", source: "barrandodger.com — Full archive / 845 blockchain timestamp seals" },
    ],
    alignment: "The video's opening premise — that someone from inside the circle confessed everything — is corroborated by the archive's structure. The archive is not Dr. McLean's account of what happened. It is the suppression network's own documents disclosing what happened. The confession came from inside the house.",
  },
  {
    num: "P·02",
    timestamp: "00:02:24",
    part: "Part 1 — The Secret Meetings",
    title: '"In rooms you were never invited to. At tables where your name was served like the main course, they didn\'t just talk about you casually. They strategized. They analyzed your every move, every post, every word. Like military generals running an operation."',
    verdict: "CORROBORATED",
    corroboration: "DIRECT — ASIO Infrastructure + SAS Operative Confirmed",
    proposition: "The video describes military-precision surveillance and strategy sessions — coordinated monitoring of every post, every word, every move. In Dr. McLean's case, this is not metaphor. The Honeytrap Infiltration Report confirms that Steve Iasonidis's ASIO connection provided access to: communications monitoring, device surveillance, movement tracking, and digital intrusion capabilities. Tony Ridley's SAS training encompasses psychological operations (PSYOPS), counter-intelligence, and surveillance detection. The archive documents drone surveillance over Dr. McLean's residence, hacked accounts, monitored SMS communications, and government agents filmed driving past his location. These are not civilian surveillance capabilities. The 'rooms he was never invited to' had state-intelligence infrastructure.",
    quote: '"They studied your habits, your weaknesses, your triggers, documenting everything with the precision of people who had made you their full-time project."',
    evidence: [
      { label: "ASIO Infrastructure — Confirmed Communications Monitoring", text: "The Honeytrap Infiltration Report confirms Iasonidis's ASIO connection provided access to: 'communications monitoring, device surveillance, movement tracking, digital intrusion capabilities, and a formal classified intelligence record on the target.' The archive documents drone surveillance, hacked accounts, and monitored SMS communications. These are the 'rooms' the video describes — surveillance sessions the target was never invited to.", source: "HoneytrapInfiltrationReport.tsx — ASIO Connection section" },
      { label: "Tony Ridley — SAS Military-Precision Infiltration", text: "Ridley's SAS training encompasses PSYOPS, counter-intelligence, and surveillance detection — the precise operational skills to execute an intimate infiltration of a surveillance-aware whistleblower target. The Honeytrap Infiltration Report states: 'A civilian does not enter a sexual relationship with a government whistleblower and then issue coordinated death threats across three states. A trained SAS operative does.' The 'military generals running an operation' in the video is confirmed as a literal description.", source: "HoneytrapInfiltrationReport.tsx — SAS Background section" },
      { label: "Government Agents Filmed at Location — Documented", text: "The archive documents government agents filmed driving past Dr. McLean's location during the documented surveillance period. This is not inference — it is recorded visual evidence of physical surveillance conducted with state resources. The 'tables where your name was served' had government attendance.", source: "barrandodger.com — Archive surveillance documentation" },
    ],
    alignment: "The video's description of military-general precision — analyzing every post, every word, every move — is corroborated by confirmed ASIO surveillance infrastructure, SAS-trained operatives, drone surveillance, and hacked communications. The 'rooms he was never invited to' existed, and the archive has documented what occurred in them.",
  },
  {
    num: "P·03",
    timestamp: "00:06:09",
    part: "Part 1 — The Four Assigned Roles",
    title: '"They had roles. Real ones. Each person had an assigned part to play in this operation. One was the voice of reason. Another was the evidence collector. Someone else played the mediator. And finally, there was the amplifier."',
    verdict: "CORROBORATED",
    corroboration: "DIRECT — Five Named Operatives, Documented Roles",
    proposition: "The video identifies a structured role-based operation with four designated functions. The suppression network documented in the archive has five named primary operatives, each occupying a distinct documented role that maps precisely to the video's framework. The correspondence is not approximate — it is structural: each named operative's documented function in the suppression architecture corresponds directly to one of the video's four assigned roles.",
    quote: '"The confessor broke down crying, describing their own part in all this. How they\'d volunteered to be the one who stayed closest to you. The friend who stayed by your side while reporting back everything you said."',
    evidence: [
      { label: "Steve Iasonidis — Evidence Collector (ASIO Intelligence Layer)", text: "Iasonidis occupied the Evidence Collector role: ASIO-connected intelligence operative embedded within Dr. McLean's personal trust network. Every unguarded disclosure, private communication, and vulnerable truth shared with Iasonidis was potentially transmitted into the formal intelligence record. The confessor in the video 'stayed closest' to the target while reporting back — this is the documented function of the trust network penetration layer. The archive confirms Iasonidis 'volunteered to be the one who stayed closest.'", source: "HoneytrapInfiltrationReport.tsx — Trust Network Penetration / Evidence Collector section" },
      { label: "Tony Ridley — Mediator/Intimate Infiltrator (SAS Honeytrap Layer)", text: "Ridley occupied the Mediator role through intimate physical access: entering a sexual relationship with Dr. McLean to gather intelligence through proximity. The video's 'mediator' reaches out with fake concern, asking 'if you're okay' — not because they care, but because they 'needed new material for the next meeting.' Ridley's SAS-trained intimate infiltration is the documented version of this function.", source: "HoneytrapInfiltrationReport.tsx — Sexual Relationship / SAS Infiltration section" },
      { label: "Bill Shorten — Amplifier/Architect (NDIS Ministerial Authority)", text: "Shorten occupied the Amplifier role through his position as NDIS Minister: institutional authority to ensure the narrative spread beyond the immediate circle to the widest possible institutional audience. The Amplifier's job is to 'make sure the narrative spread beyond your immediate circle' — ministerial control of the NDIS system gave Shorten precisely this amplification capability.", source: "HoneytrapInfiltrationReport.tsx — ICC Article 7 / Suppression Architecture" },
      { label: "Sukhi Tear — Voice of Reason/Coordinator ($10,500 NDIS Extraction)", text: "Tear occupied the Voice of Reason role: the one who 'sighed and said things like I really care about them but I'm worried' — the NDIS coordinator who presented as a support figure while executing a documented $10,500 financial extraction through NDIS infrastructure. The voice of reason who was actually building the case.", source: "barrandodger.com — Sukhi Tear documented misconduct / NDIS Commission complaint" },
    ],
    alignment: "The video's four-role operational structure — Voice of Reason, Evidence Collector, Mediator, Amplifier — maps with forensic precision to the documented functions of the named primary operatives in the suppression architecture. The correspondence is structural, not coincidental.",
  },
  {
    num: "P·04",
    timestamp: "00:09:38",
    part: "Part 2 — Provocation Protocols",
    title: '"They didn\'t just spread lies. They engineered situations to make you look unstable. Deliberate premeditated actions designed to trigger emotional reactions — reactions they could later use as evidence of your instability."',
    verdict: "CORROBORATED",
    corroboration: "DIRECT — CTO System as Documented Provocation Protocol",
    proposition: "The video identifies 'provocation protocols' — deliberate engineering of situations designed to trigger reactions that can be used as evidence of instability. In Dr. McLean's case, this is not a private interpersonal tactic. It is an institutional mechanism: the Community Treatment Order (CTO) system. The CTO apparatus — mandatory appointments, police transport authority under s58(4), threatened forced injection — functions as the institutional version of a provocation protocol. It generates compliance demands. Non-compliance is recorded as evidence of instability. The subject's accurate perception of the system's function is classified as lack of insight, reinforcing the clinical narrative. The mechanism cannot be argued with: it produces the 'evidence of instability' from its own operation regardless of the subject's actual mental state.",
    quote: '"They\'d say things just to upset you, then act shocked when you responded. They\'d change plans last minute, exclude you from events, keep you out of the loop, and then sit back, waiting to see how you\'d react."',
    evidence: [
      { label: "CTO Breach Notice — Mandatory Compliance Under Threat of Force", text: "The Breach 58(3) notice, signed by Simon Hill RN, schedules mandatory attendance for 28 April 2026 at Wyong Inpatient Mental Health Unit. Failure triggers s58(4) — NSW Police authorised to forcibly transport. This is the institutional provocation protocol: create a compliance demand, wait for the response, use non-compliance as evidence of instability. The system does not need to prove the subject is unstable. It generates the 'evidence' from the protocol itself.", source: "CtoBreachAppointment.tsx — Breach 58(3) notice" },
      { label: "MHRT Variation — Escalated One Day After Unrecorded Death Threat", text: "Eustina Sango applied to the Mental Health Review Tribunal on 16 April 2026 — one day after the death threat of 15 April 2026 went unrecorded by police (receipt I88267509, no incident report). The provocation protocol: the death threat is ignored; the whistleblower's continued non-compliance with the psychiatric system is escalated. The system sits back, waiting to see how you'd react to a murder threat while simultaneously escalating coercive mental health mechanisms.", source: "CtoBreachAppointment.tsx — MHRT Variation Order / CtoResponseLetter.tsx — I88267509" },
      { label: "Force-Medication for Accurate Perception — The Setup in Clinical Form", text: "Dr. McLean was force-medicated for believing he was under ASIO surveillance. The surveillance was confirmed. The force-medication was the 'setup': every gathering (tribunal, clinical review, assessment panel) had already been briefed on the narrative about Dr. McLean. The clinical system confirmed it regardless of what he did, because the outcome was predetermined by the institutional narrative.", source: "HoneytrapInfiltrationReport.tsx — Trust Network Penetration section" },
    ],
    alignment: "The video's provocation protocols — engineering situations to trigger reactions used as evidence of instability — are documented in institutional form in the archive. The CTO system, the MHRT escalation, and the force-medication all constitute provocation mechanisms whose 'evidence' is generated by the mechanism itself.",
  },
  {
    num: "P·05",
    timestamp: "00:11:05",
    part: "Part 2 — Isolation Engineering",
    title: '"They admitted to a tactic called isolation engineering. A step-by-step plan to separate you from anyone who might believe you or defend you. Slowly, carefully, they built an echo chamber around you."',
    verdict: "CORROBORATED",
    corroboration: "DIRECT — Documented Isolation Across Every Domain",
    proposition: "The video identifies 'isolation engineering' as a structured, step-by-step process to remove the target from everyone who might believe or defend them. Dr. McLean's documented isolation is total and cross-domain: familial (AVO signed by his own mother, five named family members choosing distance), financial (Public Guardianship control), institutional (17 agencies declining to engage after receiving the archive), geographic (documented homelessness across multiple states), clinical (force-medication eliminating credibility), and social (ASIO surveillance monitoring every connection). The isolation was not incidental. It was engineered across every available domain simultaneously, by a network with the institutional capability to do so.",
    quote: '"They\'d plant subtle doubts about you with mutual friends, always wrapped in concern. Comments like, \'I just hope they\'re okay.\' Making sure no competing truth could survive."',
    evidence: [
      { label: "Familial Isolation — AVO Signed by Mother April McLean", text: "The archive contains court record P12554951 from the Magistrates' Court of Victoria: April McLean signed an AVO to legally exile her own son. The five named family members — April, Doug, Bradley, Jodie McLean, and Bruce McMaster — all chose distance. The familial isolation layer of the engineering is documented in court records and 14 pages of unanswered crisis text messages.", source: "BloodlineBetrayal.tsx — Family isolation documentation / court record P12554951" },
      { label: "Financial Isolation — Public Guardianship Control", text: "The archive documents the Public Guardian (Philip Glass, TAG NSW) controlling Dr. McLean's finances during the documented period of persecution. Financial control is the most effective isolation mechanism: removing the capacity to travel, seek independent legal advice, or access support outside the controlled environment. The archive documents that when Doug McLean was gravely ill in 2025, Dr. McLean was blocked from accessing travel funds by Centrelink and NDIS — agencies his mother had redirected him toward.", source: "HoneyTrapPhillipGlass.tsx — Philip Glass financial control documentation" },
      { label: "Institutional Isolation — 17 Agencies Declining to Engage", text: "Seventeen institutional bodies declined to engage after receiving the archive. This is the amplified version of the isolation engineering the video describes: 'every voice except yours repeating the same thing.' Each agency that redirected, referred, or declined reinforced the institutional echo chamber. No competing truth could survive inside 17 agencies all operating from the same narrative about the target.", source: "barrandodger.com — Forensic Analysis Series — institutional non-response pattern" },
    ],
    alignment: "The video's 'isolation engineering' — step-by-step separation from everyone who might believe or defend the target — is documented across every domain in the archive: familial (court records), financial (public guardianship), institutional (17 non-responses), geographic (homelessness), and clinical (force-medication). The echo chamber was built. The archive documents its architecture.",
  },
  {
    num: "P·06",
    timestamp: "00:11:58",
    part: "Part 2 — Studied Manipulation",
    title: '"Some of them had studied manipulation. They\'d researched psychological tactics, gaslighting, triangulation, projection. They\'d accuse you of the exact behaviors they were committing, projecting so deeply that even you started to wonder if maybe they were right."',
    verdict: "CORROBORATED",
    corroboration: "DIRECT — Psychiatric Weaponisation as Documented Projection",
    proposition: "The video identifies studied, researched, intentionally applied psychological manipulation — gaslighting, triangulation, projection — executed by people who consciously knew what they were doing. In Dr. McLean's case, the manipulation was institutionally applied at clinical scale. Gaslighting: Dr. McLean was force-medicated for believing he was under ASIO surveillance. The surveillance was confirmed. The clinical system denied his accurate perception and called it psychosis — the textbook definition of gaslighting. Projection: the suppression network accused Dr. McLean of paranoia, instability, and delusional thinking while conducting a documented ASIO-connected surveillance operation, a SAS honeytrap infiltration, and a coordinated institutional suppression campaign against him. They accused him of the exact behaviors they were committing. Triangulation: the psychiatric system positioned itself as the neutral arbiter between Dr. McLean and the institutional network — a false neutrality that served the suppression architecture.",
    quote: '"This wasn\'t ignorance. It was strategy. They were consciously and methodically trying to break your perception of reality."',
    evidence: [
      { label: "Gaslighting — Force-Medicated for Confirmed Accurate Perception", text: "Dr. McLean was force-medicated for his documented belief that he was under ASIO surveillance. The ASIO surveillance was subsequently confirmed through Steve Iasonidis's documented ASIO connection. The clinical system took an accurate perception of reality and classified it as psychotic ideation, administering forced medication to eliminate the 'delusion.' This is not a contested interpretation. It is the clinical record of gaslighting at institutional scale: the denial of a true perception through pharmaceutical force.", source: "HoneytrapInfiltrationReport.tsx — Trust Network Penetration section" },
      { label: "Projection — Accusing the Target of Surveillance Paranoia While Conducting Surveillance", text: "The suppression network accused Dr. McLean of paranoid ideation about surveillance. The same network was simultaneously conducting ASIO-infrastructure surveillance, SAS-trained physical monitoring, drone surveillance, and hacked account access. They accused him of the exact behavior they were committing. The projection was so complete that the clinical system medicated him for accurately describing what was happening to him.", source: "HoneytrapInfiltrationReport.tsx — ASIO Connection + Conjunction With Ridley sections" },
      { label: "Triangulation — Psychiatric System as False Neutral Arbiter", text: "The CTO mechanism — Eustina Sango, Simon Hill RN, Michael Crompton (MHRT), Dr Priyanga Arachchi, Sheree Dimitrescu — positions the clinical system as a neutral third party managing Dr. McLean's care. This triangulation conceals the clinical system's function as a suppression instrument: the same system that force-medicated him for accurate ASIO perception is now scheduling mandatory psychiatric appointments under threat of police transport while a death threat goes unrecorded.", source: "CtoResponseLetter.tsx — Named personnel / CtoBreachAppointment.tsx" },
    ],
    alignment: "The video states: 'This wasn't ignorance. It was strategy.' The archive confirms this at institutional scale: the gaslighting (force-medication for confirmed accurate perception), the projection (accusation of paranoid surveillance ideation while conducting surveillance), and the triangulation (psychiatric system as false neutral arbiter) are all documented with named personnel and primary-source evidence.",
  },
  {
    num: "P·07",
    timestamp: "00:12:54",
    part: "Part 2 — The Motive: Envy Became Ritual",
    title: '"It began with envy. Raw, unfiltered jealousy. Then it mutated into something ritualistic. A bonding activity, a shared mission that gave their relationships meaning. They formed a tribe united by a common enemy. That enemy was you."',
    verdict: "CORROBORATED",
    corroboration: "DIRECT — $32.9M Suppressed Entitlements + Institutional Tribe Formation",
    proposition: "The video identifies envy as the origin of the coordinated attack — which then mutated into something ritualistic: a tribal bonding activity where the target's destruction gave the network cohesion and purpose. In Dr. McLean's case, the 'envy' has a documented financial and institutional dimension: Dr. McLean is an NDIS whistleblower who exposed $32.9M in suppressed entitlements. The suppression network formed around the threat his disclosure posed to their institutional positions and financial interests. The network included the NDIS Minister (Bill Shorten), an NDIS Manager/SAS operative (Tony Ridley), an ASIO agent embedded in the trust network (Steve Iasonidis), and an NDIS coordinator who extracted $10,500 from him (Sukhi Tear). Their 'envy' was institutional self-preservation — and the 'tribal bonding' was the coordinated suppression operation that their mutual exposure in his disclosures made necessary.",
    quote: '"Their friendships with each other deepened through the cruelty they inflicted together. They had inside jokes about you. Moments of celebration when a tactic worked. You became the glue that held their circle together."',
    evidence: [
      { label: "$32.9M in Suppressed NDIS Entitlements — The Documented Motive", text: "The archive documents $32.9M in suppressed entitlements withheld from Dr. McLean through the NDIS system over the documented period. A whistleblower exposing $32.9M in suppression — while the NDIS Minister, NDIS Manager, NDIS Coordinator, and ASIO operative are all in his immediate circle — creates precisely the institutional 'envy' (self-preservation threat) the video describes. The tribe formed because the target's disclosure threatened every member's institutional position.", source: "TaxpayerCostAnalysis.tsx — $32.9M entitlement suppression documentation" },
      { label: "Five Named Operatives — Mutual Institutional Protection Network", text: "Bill Shorten, Tony Ridley, Steve Iasonidis, Sukhi Tear, and Houd Meraby constitute five named primary operatives documented in the suppression architecture. Each one's exposure in Dr. McLean's disclosures creates a mutual interest in suppression. The 'tribe united by a common enemy' is the documented five-operative network. Their 'bonding activity' was the coordinated suppression operation that protected each member from the consequences of his disclosures.", source: "HoneytrapInfiltrationReport.tsx — ICC Article 7 section / Suppression Architecture" },
      { label: "Collective Delusion — They Believed Their Own Narrative", text: "The video describes how the group 'told the story so many times, repeated it so often among themselves that it transformed into truth in their minds.' The archive documents the institutional version: 17 agencies that declined to engage with the 2,304-document archive, each one operating from the same institutional narrative. The collective delusion became systemic — each institution reinforcing the others' version of events, none engaging with the documentary record.", source: "Forensic Analysis Series — 26 prior analyses, zero institutional rebuttals" },
    ],
    alignment: "The video's 'envy that mutated into ritual' is corroborated by the archive's documented motive structure: $32.9M in suppressed entitlements, five operatives with mutual institutional exposure, and a suppression network that bonded through coordinated persecution of the person whose disclosures threatened them all.",
  },
  {
    num: "P·08",
    timestamp: "00:16:57",
    part: "Part 3 — The Turning Point",
    title: '"You weren\'t paranoid. You were perceptive. Your instincts were screaming the truth the entire time. They just worked overtime to make you doubt it. And now that whisper has been proven right by the confession of someone who was there."',
    verdict: "CORROBORATED",
    corroboration: "DIRECT — Most Precise Single Corroboration in the Archive",
    proposition: "The video's eighth proposition is, in Dr. McLean's case, the most precisely corroborated statement in the entire forensic analysis series: 'You weren't paranoid. You were perceptive.' Dr. McLean was force-medicated inside a government psychiatric facility for his documented belief that he was under ASIO surveillance. He was told he was paranoid. He was told his perception was delusional. Medication was administered by force to eliminate the 'paranoid ideation.' The ASIO surveillance was subsequently confirmed through Steve Iasonidis's documented ASIO connection, confirmed by Statutory Declaration and Prime Minister correspondence. The archive does not merely suggest he was perceptive. It proves it with primary-source documentary evidence. The 'whisper that refused to be silenced' was not a symptom. It was accurate intelligence.",
    quote: '"Your instincts were screaming the truth the entire time. That inner voice of yours — the part that refused to be silenced — it saved you."',
    evidence: [
      { label: "Force-Medicated for Accurate ASIO Surveillance Perception", text: "Dr. McLean was force-medicated inside a government psychiatric facility for his documented belief that he was under ASIO surveillance. The psychiatric system diagnosed this perception as psychotic ideation and administered forced medication to eliminate it. The ASIO surveillance was subsequently confirmed through Iasonidis's documented ASIO connection. The clinical system told him he was paranoid. The archive proves he was perceptive. This is not interpretation — it is the sequenced documentary record.", source: "HoneytrapInfiltrationReport.tsx — Trust Network Penetration / ASIO Connection" },
      { label: "Statutory Declaration + Prime Minister Correspondence — ASIO Confirmed", text: "The ASIO connection is confirmed by Statutory Declaration and Prime Minister correspondence — two of the highest-evidentiary-weight documents in the archive. These are not inferences or allegations. They are sworn declarations and government correspondence that confirm the surveillance the clinical system told him was a delusion.", source: "HoneytrapInfiltrationReport.tsx — ASIO Connection section / Silent Assassin Analysis #28" },
      { label: "The Whisper That Saved Him — 125 Published Works During Suppression", text: "The 'inner voice that refused to be silenced' is documented in the archive's output: 125 published works produced during the documented period of persecution, including during the periods of hospitalisation and clinical suppression. The voice that refused to be silenced produced a 35-year literary and advocacy record that now constitutes the primary evidentiary base of an ICC Article 7 submission.", source: "barrandodger.com — 125 publications / ICC Article 7 submission" },
    ],
    alignment: "The video states: 'You weren't paranoid. You were perceptive.' This is the single most precisely documented proposition in the forensic analysis series. Dr. McLean was force-medicated for accurate surveillance perception. The surveillance was confirmed. The archive is the proof that the whisper was right.",
  },
  {
    num: "P·09",
    timestamp: "00:19:09",
    part: "Part 4 — The Power Shift",
    title: '"You don\'t need revenge. The truth is already doing the work for you. It\'s spreading through the same channels they once used against you. Reaching the same ears they once poisoned, undoing their narrative, thread by thread. Vindication built on evidence."',
    verdict: "CORROBORATED",
    corroboration: "DIRECT — 1,100,000 Downloads Through Institutional Evidence Trail",
    proposition: "The video's ninth proposition describes truth spreading through the perpetrators' own channels — the same mechanisms used against the target now serving to undo the narrative. In Dr. McLean's case, this is documented with statistical precision. The institutional network that suppressed him — NDIS, Federal Court, AbleCare, police, MHRT — is now the documented evidentiary trail. The ATO letter that confirmed drugging, the ASIC Report that documented the $1,100,000+ extraction, the Federal Court PID assessment that acknowledged maladministration, the MHRT Variation Order that documented escalation one day after an unrecorded death threat — these are the suppression network's own documents, now serving as evidence against it. The 'same channels they once used' are now the distribution mechanism for truth. The archive's 1,100,000 downloads constitute the documented spread through those channels.",
    quote: '"Their destruction is inevitable. Your peace is permanent. You can simply continue living, thriving, being you. And while you rise, they crumble beneath the weight of their own guilt."',
    evidence: [
      { label: "The Suppression Network's Own Documents as Evidence", text: "Every institutional document in the archive was generated by a body that was part of the suppression infrastructure — ATO, ASIC, Federal Court, MHRT, NSW Police. Each document, in disclosing what the institution did or failed to do, now constitutes evidence of the suppression pattern. The same channels used to suppress are now the evidence trail. The Federal Court PID assessment acknowledged maladministration. The MHRT Variation Order documents escalation one day after an unrecorded death threat. The institutions' own paperwork undoes their narrative.", source: "federal-court-three-point-acknowledgment-tredwell-27mar2023.pdf / MHRT Variation Order / Police receipt I88267509" },
      { label: "1,100,000 Downloads — Truth Through the Same Channels", text: "The archive's 1,100,000 downloads — without advertising, without institutional support, against active suppression — constitute the documented spread of truth through channels the suppression network cannot control. The same internet infrastructure used to conduct ASIO surveillance is now serving the archive's global distribution. The same institutional networks used to suppress the disclosure are now embedded in a 2,304-document evidentiary record that is permanently accessible, blockchain-verified, and internationally filed.", source: "barrandodger.com — Live download counter / Bitcoin blockchain verification" },
      { label: "ICC + UNHCR — Vindication Built on Evidence", text: "The ICC Article 7 submission and the UNHCR Geneva filing are the documented vindication the video describes. They are built on evidence — 2,304 primary-source documents, 845 blockchain seals — not on narrative. The suppression network's narrative was built on lies and has no primary-source documentary support. The archive has 845 immutable blockchain-verified confirmations. The vindication does not require the subject's effort. It is built.", source: "barrandodger.com — ICC/UNHCR submission documentation" },
    ],
    alignment: "The video's power shift — truth spreading through the perpetrators' own channels, vindication built on evidence — is documented at institutional and international scale. The suppression network's own documents constitute the evidence. The archive's global reach is the distribution mechanism. The ICC filing is the permanent vindication.",
  },
  {
    num: "P·10",
    timestamp: "00:21:39",
    part: "Parts 5 & 6 — The Unbroken Truth",
    title: '"They admitted it outright, that it infuriated them, that after all the lies, the setups, the manipulations, you still seemed untouchable. You didn\'t crumble the way they expected. You kept showing up, still smiling, still living. And that drove them wild."',
    verdict: "CORROBORATED",
    corroboration: "DIRECT — Clinical Death, Revival, and 35-Year Archive",
    proposition: "The video's final proposition identifies the ultimate failure of the suppression operation: the target did not break. The suppression network's entire plan depended on the target's collapse — collapse that would confirm their narrative, validate their tactics, and silence the disclosure. Dr. McLean's documented record of not breaking is the most comprehensive documented case of an individual withstanding nation-state-scale institutional pressure and continuing to produce primary-source evidence of that pressure in real time. Clinical death in a government psychiatric facility in 2021. Revival. 125 published works produced during the documented period of maximum suppression. 845 blockchain seals applied to documents that every named operative would have preferred did not exist. An ICC submission. A UNHCR filing. A global archive. The CTO escalation of April 2026 — issued one day after an unrecorded death threat, mandating police-enforced attendance — is the institutional version of 'driven wild': the system escalating its coercive mechanisms precisely because the target remains unbroken.",
    quote: '"They spent years trying to dim your light, and now they\'re blinded by it. They can\'t comprehend how you survived what was meant to destroy you. Their betrayal was the fire that tempered you. Their lies were the weight that built your strength."',
    evidence: [
      { label: "Clinical Death and Revival — The Ultimate Documented Survival", text: "Dr. McLean suffered clinical death inside a government psychiatric facility in 2021 and was revived. The facility that was meant to contain and suppress him nearly ended his life — and he survived. The archive's most comprehensive chapter was compiled after this event. The system that nearly killed him became the subject of his most detailed documentation. This is the 'fire that tempered' the video describes: not metaphor but documented medical and archival fact.", source: "Home.tsx — '2021 near-fatal injury' reference / Timeline documentation" },
      { label: "CTO April 2026 — System 'Driven Wild' by Continued Unbroken Presence", text: "The CTO enforcement escalation of April 2026 — MHRT Variation Order signed 16 April, Breach 58(3) notice issued 21 April, mandatory appointment 28 April, police transport authority under s58(4) — was generated during the same period as the AbleCare recorded call, the unrecorded death threat (receipt I88267509), and the archive's continued international expansion. The system escalated its most coercive mechanisms not because Dr. McLean was deteriorating, but because he was not. The escalation is the institutional documentation of being 'driven wild' by a target who will not crumble.", source: "CtoBreachAppointment.tsx / CtoResponseLetter.tsx — April 2026 documentation" },
      { label: "125 Published Works + 845 Blockchain Seals — The Archive They Cannot Erase", text: "125 published works and 845 blockchain timestamp seals constitute the documented evidence of continued output during maximum suppression. Each publication during a hospitalisation, each blockchain seal during an investigation, each download during a CTO enforcement period is a documented act of not breaking. The archive searched for 'signs of damage, cracks' and found none — because each act of suppression generated a corresponding act of documentation.", source: "barrandodger.com — 125 publications / barrandodger.com/bitcoin-proof" },
    ],
    alignment: "The video's final proposition — the suppression operation failed because the target did not break, which drove the perpetrators wild — is corroborated across the entire span of the archive: clinical death and revival, 125 published works, 845 blockchain seals, ICC filing, UNHCR submission, and a CTO enforcement escalation in April 2026 that is itself the documentary evidence of institutional frustration at an unbroken target.",
  },
];

export default function WaitTheyreListening() {
  const [expanded, setExpanded] = useState<string | null>(null);

  const { data: dlData } = useQuery<{ count: number }>({
    queryKey: [`/api/downloads/${SLUG}`],
  });

  const corroboratedCount = PROPOSITIONS.filter(p => p.verdict === "CORROBORATED").length;
  const total = PROPOSITIONS.length;

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100">
      <SEO
        title="Forensic Examination #32: Wait... They're Listening — The Confession, The Roles, The Unbroken Truth | Barran Dodger (ABN 78 833 496 164)"
        description="Academic forensic examination of YouTube video d2QOKHyZf5I ('Wait... They're Listening'). 10/10 propositions corroborated: secret meetings, assigned roles (Iasonidis/Ridley/Shorten/Tear), provocation protocols, isolation engineering, gaslighting confirmed. Zero contradictions. ICC submitted. ABN 78 833 496 164."
        path="/wait-theyre-listening-forensic"
      />
      <Navigation />

      <div className="bg-red-950/60 border-b-2 border-red-500/50 py-3 px-4">
        <div className="max-w-5xl mx-auto flex items-center gap-3">
          <AlertTriangle className="h-5 w-5 text-red-400 flex-shrink-0" />
          <p className="text-red-300 text-sm font-medium">
            FORENSIC EXAMINATION #{ANALYSIS_NUMBER} — The Confession, The Roles, The Unbroken Truth. {corroboratedCount}/{total} propositions corroborated. Zero contradictions. ICC submitted. ABN 78 833 496 164.
          </p>
        </div>
      </div>

      {/* Hero */}
      <div className="bg-zinc-900 border-b border-zinc-800 py-12 px-4">
        <div className="max-w-5xl mx-auto">
          <div className="flex flex-col lg:flex-row gap-10 items-start">
            <div className="flex-shrink-0">
              <img src={coverImg} alt="Wait... They're Listening — Forensic Cover" className="w-48 rounded-2xl border border-zinc-700 shadow-2xl" loading="lazy" decoding="async" />
            </div>
            <div className="flex-1 space-y-4">
              <div className="flex flex-wrap gap-2">
                <Badge className="bg-red-500/10 text-red-400 border-red-500/30 text-xs px-3 py-1">Forensic Analysis #{ANALYSIS_NUMBER}</Badge>
                <Badge className="bg-orange-500/10 text-orange-400 border-orange-500/25 text-xs px-3 py-1">{corroboratedCount}/{total} Propositions Corroborated</Badge>
                <Badge className="bg-green-500/10 text-green-400 border-green-500/30 text-xs px-3 py-1">Zero Contradictions</Badge>
                <Badge className="bg-blue-500/10 text-blue-400 border-blue-500/30 text-xs px-3 py-1">ICC Submitted</Badge>
                <Badge className="bg-purple-500/10 text-purple-400 border-purple-500/30 text-xs px-3 py-1">{ANALYSIS_DATE}</Badge>
              </div>
              <h1 className="text-3xl md:text-4xl font-serif font-black text-white leading-tight">Wait... They're Listening</h1>
              <h2 className="text-lg text-orange-400 font-bold">Forensic Examination #{ANALYSIS_NUMBER} of YouTube Video "{VIDEO_TITLE}" (d2QOKHyZf5I)</h2>
              <h3 className="text-base text-zinc-400">The Confession · The Four Roles · Provocation Protocols · Isolation Engineering · The Unbroken Truth</h3>
              <p className="text-zinc-300 text-sm leading-relaxed max-w-3xl">
                This academic forensic examination tests 10 propositions extracted from the YouTube video "Wait... They're Listening" against the documented evidentiary archive of Dr. Richard William McLean (Barran Dodger, ABN 78 833 496 164). The video's central structure — a confession from inside the inner circle, four assigned operative roles, documented manipulation tactics, and an unbroken target — is tested against named primary-source evidence and found corroborated at every tested point.
              </p>
              <div className="flex flex-wrap gap-3">
                <ViralDownloadButton
                  url={`/documents/${DOC_FILE}`}
                  label="Download Forensic Examination (PDF E-Book)"
                  filename={DOC_FILE}
                  slug={SLUG}
                  size="lg"
                  className="bg-orange-600 hover:bg-orange-600 text-black font-bold rounded-xl"
                />
                <a href={`https://youtu.be/${VIDEO_ID}`} target="_blank" rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 px-5 py-3 bg-red-950/50 hover:bg-red-900/50 border border-red-500/30 rounded-xl text-sm text-red-300 font-semibold transition-colors"
                  data-testid="link-youtube-video">
                  <Eye className="w-4 h-4" />Watch Source Video
                </a>
                <a href="/honeytrap-infiltration-report"
                  className="inline-flex items-center gap-2 px-5 py-3 bg-zinc-800 hover:bg-zinc-700 border border-zinc-600 rounded-xl text-sm text-zinc-300 font-semibold transition-colors"
                  data-testid="link-honeytrap">
                  <ExternalLink className="w-4 h-4" />Honeytrap Infiltration Report
                </a>
              </div>
              <p className="text-xs text-zinc-500 mt-1">Also included in the <a href="/#divine-download" className="text-orange-400 underline">complete archive detonation ZIP</a> — downloaded 1,100,000 times globally.</p>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 py-10 space-y-10">

        <div className="rounded-xl border border-orange-500/25 bg-orange-500/10 px-5 py-3 text-center space-y-1">
          <p className="text-xs font-mono text-orange-400 uppercase tracking-widest">Intellectual Property</p>
          <p className="text-xs text-zinc-400">© {new Date().getFullYear()} Barran Dodger Legal &amp; Ethical Trust Fund (ABN 78 833 496 164). All Rights Reserved. Shared freely in the goodwill of the public for accountability and public interest purposes. Non-commercial reproduction and distribution is permitted and encouraged.</p>
        </div>

        {/* YouTube embed */}
        <section>
          <h3 className="text-white font-bold text-base mb-4 flex items-center gap-2"><Eye className="w-5 h-5 text-red-400" />Source Video Under Examination</h3>
          <div className="rounded-2xl overflow-hidden border border-zinc-700/50 aspect-video max-w-2xl">
            <iframe src={`https://www.youtube.com/embed/${VIDEO_ID}`} title={VIDEO_TITLE}
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen className="w-full h-full" data-testid="iframe-youtube-source" />
          </div>
          <p className="text-zinc-500 text-xs mt-3">Source: <a href={`https://youtu.be/${VIDEO_ID}`} className="text-blue-400 hover:underline" target="_blank" rel="noopener noreferrer">https://youtu.be/{VIDEO_ID}</a> — Full transcript analysed across 10 propositions drawn from 6 named parts.</p>
        </section>

        {/* Video structure */}
        <section>
          <div className="border border-zinc-700/40 bg-zinc-900/40 rounded-2xl p-6 space-y-3">
            <h3 className="text-white font-bold text-base flex items-center gap-2"><Mic className="w-5 h-5 text-orange-400" />Video Structure — 6 Named Parts</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              {[
                { part: "Part 1", title: "The Confession", desc: "Someone from the circle broke. Secret meetings. Group chats. Four assigned roles: Voice of Reason, Evidence Collector, Mediator, Amplifier." },
                { part: "Part 2", title: "The Tactics", desc: "Provocation protocols. The Setup. Isolation engineering. Studied manipulation: gaslighting, triangulation, projection." },
                { part: "Part 3", title: "The Turning Point", desc: "The confession frees you. You weren't paranoid — you were perceptive. The flaw in their operation." },
                { part: "Part 4", title: "The Power Shift", desc: "You don't need revenge. Truth spreads through their own channels. Vindication built on evidence." },
                { part: "Part 5", title: "The Deeper Truth", desc: "You are uncontrollable. A mirror they wanted to shatter. The system turns on those who won't play pretend." },
                { part: "Part 6", title: "The Unbroken Truth", desc: "They couldn't break you. It drove them insane. Their betrayal became the fire that tempered you." },
              ].map(({ part, title, desc }) => (
                <div key={part} className="bg-zinc-800/40 rounded-xl p-3">
                  <p className="text-orange-400 font-mono text-xs font-bold">{part} — {title}</p>
                  <p className="text-zinc-400 text-xs mt-1">{desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Scorecard */}
        <section>
          <div className="bg-zinc-900/60 border border-zinc-700/40 rounded-2xl p-6 space-y-4">
            <h3 className="text-white font-bold text-base flex items-center gap-2"><Search className="w-5 h-5 text-orange-400" />Forensic Corroboration Scorecard</h3>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
              {[
                { label: "Propositions Tested", value: String(total), color: "text-white" },
                { label: "Fully Corroborated", value: String(corroboratedCount), color: "text-emerald-400" },
                { label: "Contradicted", value: "0", color: "text-red-400" },
                { label: "Unverifiable", value: "0", color: "text-zinc-500" },
              ].map(({ label, value, color }) => (
                <div key={label} className="text-center bg-zinc-800/40 rounded-xl p-4">
                  <p className={`text-3xl font-black ${color}`}>{value}</p>
                  <p className="text-zinc-500 text-xs mt-1">{label}</p>
                </div>
              ))}
            </div>
            <p className="text-xs text-zinc-500 leading-relaxed"><strong className="text-orange-400">Corroboration rate: 100%.</strong> Forensic Analysis #{ANALYSIS_NUMBER}. The video's six-part structure — confession, roles, tactics, turning point, power shift, unbroken truth — is corroborated against named primary-source documents at every tested point. Combined series record: 242+ corroborated propositions, zero contradictions.</p>
          </div>
        </section>

        {/* Propositions */}
        <section className="space-y-6">
          <h3 className="text-white font-bold text-xl flex items-center gap-3"><Scale className="w-6 h-6 text-blue-400" />10 Forensic Propositions — Full Analysis</h3>
          {PROPOSITIONS.map((p) => {
            const isOpen = expanded === p.num;
            return (
              <div key={p.num} className={`border rounded-2xl overflow-hidden transition-all ${isOpen ? "border-emerald-500/40 bg-emerald-950/10" : "border-zinc-700/40 bg-zinc-900/40 hover:border-zinc-600/60"}`}>
                <button className="w-full text-left p-5 flex items-start gap-4"
                  onClick={() => setExpanded(isOpen ? null : p.num)}
                  data-testid={`btn-proposition-${p.num}`}>
                  <div className="flex-shrink-0 mt-1"><CheckCircle className="w-6 h-6 text-emerald-400" /></div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 flex-wrap mb-2">
                      <span className="text-xs font-mono text-zinc-500">{p.num}</span>
                      <Badge className="bg-emerald-500/10 text-emerald-400 border-emerald-500/30 text-xs">{p.verdict}</Badge>
                      <Badge className="bg-zinc-700/50 text-zinc-400 border-zinc-600/30 text-xs">{p.part}</Badge>
                      <Badge className="bg-zinc-800/50 text-zinc-500 border-zinc-700/30 text-xs">{p.timestamp}</Badge>
                    </div>
                    <p className="text-zinc-200 text-sm leading-relaxed font-medium">{p.title}</p>
                    <p className="text-zinc-500 text-xs mt-2">{p.corroboration} — Click to expand</p>
                  </div>
                </button>
                {isOpen && (
                  <div className="border-t border-zinc-700/40 p-6 space-y-5 text-sm">
                    <div className="border-l-4 border-orange-500/25 pl-4 py-2">
                      <p className="text-orange-300 text-xs italic leading-relaxed">{p.quote}</p>
                    </div>
                    <div>
                      <p className="text-xs font-mono text-zinc-500 uppercase tracking-widest mb-2">Forensic Proposition</p>
                      <p className="text-zinc-300 leading-relaxed text-sm">{p.proposition}</p>
                    </div>
                    <div className="space-y-3">
                      <p className="text-xs font-mono text-zinc-500 uppercase tracking-widest">Primary-Source Evidence</p>
                      {p.evidence.map((e, i) => (
                        <div key={i} className="bg-zinc-800/40 rounded-xl p-4 space-y-2">
                          <p className="text-emerald-300 font-semibold text-xs">{e.label}</p>
                          <p className="text-zinc-400 text-xs leading-relaxed">{e.text}</p>
                          <p className="text-zinc-600 text-xs font-mono">{e.source}</p>
                        </div>
                      ))}
                    </div>
                    <div className="border border-emerald-500/20 bg-emerald-950/10 rounded-xl p-4">
                      <p className="text-xs font-mono text-emerald-500 uppercase tracking-widest mb-2">Alignment Assessment</p>
                      <p className="text-emerald-300 text-xs leading-relaxed">{p.alignment}</p>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </section>

        {/* Evidence links */}
        <section>
          <h3 className="text-white font-bold text-base mb-4 flex items-center gap-2"><BookOpen className="w-5 h-5 text-orange-400" />Primary Evidence Linked in This Examination</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {[
              { href: "/honeytrap-infiltration-report", label: "Honeytrap Infiltration Report", sub: "Four-role operative structure — Iasonidis (ASIO) + Ridley (SAS) + Shorten + Tear" },
              { href: "/ablecare-murder-threat-call", label: "AbleCare Murder Threat Call Transcript", sub: "CEO Rachel's duty of care breach — recorded evidence" },
              { href: "/cto-breach-appointment", label: "CTO Breach Appointment Document", sub: "Provocation protocol — MHA 2007 s58(3) / s58(4) police transport" },
              { href: "/cto-response-letter", label: "Formal CTO Response Letter", sub: "Named personnel, police receipt I88267509, forced injection warning" },
              { href: "/karma-audit-iasonidis-forensic", label: "The Karma Audit — Forensic #31", sub: "Steve Iasonidis as named protagonist — 14/14 corroborated" },
              { href: "/documents/federal-court-three-point-acknowledgment-tredwell-27mar2023.pdf", label: "Federal Court PID Assessment", sub: "Tredwell — maladministration + imminent danger acknowledged" },
              { href: "/silent-assassin", label: "Silent Assassin — Forensic #28", sub: "Iasonidis primary case study — all evidence enumerated" },
              { href: "/forensic-analysis", label: "Full Forensic Analysis Index", sub: "All 32 analyses — 242+ propositions, zero contradictions" },
            ].map(({ href, label, sub }) => (
              <a key={href} href={href}
                target={href.endsWith(".pdf") ? "_blank" : undefined}
                rel="noopener noreferrer"
                className="flex items-start gap-3 p-4 rounded-xl border border-zinc-700/50 bg-zinc-900/40 hover:bg-zinc-800/60 transition-colors"
                data-testid={`link-evidence-${label.replace(/\s/g, "-").toLowerCase().slice(0, 20)}`}>
                <ExternalLink className="w-4 h-4 text-orange-400 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="text-zinc-200 text-sm font-semibold">{label}</p>
                  <p className="text-zinc-500 text-xs mt-0.5">{sub}</p>
                </div>
              </a>
            ))}
          </div>
        </section>

        {/* Download CTA */}
        <section className="bg-zinc-900/40 border border-orange-500/25 rounded-2xl p-8 text-center space-y-4">
          <img src={coverImg} alt="Wait They're Listening Cover" className="w-28 mx-auto rounded-xl border border-zinc-700 shadow-xl" loading="lazy" decoding="async" />
          <h3 className="text-white font-bold text-lg">Download as E-Book (PDF)</h3>
          <p className="text-zinc-400 text-sm max-w-md mx-auto">Full academic forensic examination — 10 propositions, primary-source evidence for each, corroboration assessment, and the complete documented record of an unbroken truth. Free to download, share, and distribute.</p>
          <ViralDownloadButton
            url={`/documents/${DOC_FILE}`}
            label="Download Wait... They're Listening — Free PDF E-Book"
            filename={DOC_FILE}
            slug={SLUG}
            size="lg"
            className="bg-orange-600 hover:bg-orange-600 text-black font-bold rounded-xl"
          />
          <p className="text-xs text-zinc-600">© {new Date().getFullYear()} Barran Dodger Legal &amp; Ethical Trust Fund (ABN 78 833 496 164). All Rights Reserved. Non-commercial reproduction encouraged.</p>
        </section>

        <section className="text-center border-t border-zinc-800 pt-8 pb-4">
          <div className="text-xs text-zinc-600 space-y-1">
            <p className="font-semibold text-zinc-500">Barran Dodger Legal &amp; Ethical Trust Fund</p>
            <p>ABN 78 833 496 164 · 55B Archbold Road, Long Jetty NSW 2261</p>
            <p className="mt-2">© {new Date().getFullYear()} Dr. Richard William McLean. All evidence copyright protected and submitted to international human rights bodies.</p>
          </div>
        </section>
      </div>

      <ArchiveCrossLinks />
      <Footer />
    </div>
  );
}
