const BASE = "https://barrandodger.com";
const NOW = new Date().toISOString().split("T")[0];
const LAST_WEEK = new Date(Date.now() - 7 * 86400000).toISOString().split("T")[0];

type Entry = {
  loc: string;
  lastmod?: string;
  changefreq?: string;
  priority?: number;
  news?: { title: string; date: string };
  images?: Array<{ loc: string; title: string }>;
};

const FORENSIC_SLUGS = [
  ["bro-this-isnt-a-coincidence", "Forensic Analysis #1 — Bro This Isn't A Coincidence", "2025-01-01"],
  ["chosen-ones-enough-is-enough", "Forensic Analysis #2 — Chosen Ones Enough Is Enough", "2025-01-08"],
  ["no-one-could-be-that-smart", "Forensic Analysis #3 — No One Could Be That Smart", "2025-01-15"],
  ["the-divine-exam", "Forensic Analysis #4 — The Divine Exam", "2025-01-22"],
  ["silent-checkmate", "Forensic Analysis #5 — Silent Checkmate", "2025-01-29"],
  ["now-everybody-knows", "Forensic Analysis #6 — Now Everybody Knows", "2025-02-05"],
  ["chosen-one-outcast-leader", "Forensic Analysis #7 — Chosen One Outcast Leader", "2025-02-12"],
  ["someone-slipped-up", "Forensic Analysis #8 — Someone Slipped Up", "2025-02-19"],
  ["they-fumbled-you", "Forensic Analysis #9 — They Fumbled You", "2025-02-26"],
  ["fbi-precision", "Forensic Analysis #10 — FBI Precision", "2025-03-05"],
  ["clock-strikes-back", "Forensic Analysis #11 — The Clock Strikes Back", "2025-03-12"],
  ["untouchable", "Forensic Analysis #12 — Untouchable (33 Agents)", "2025-03-19"],
  ["final-blow", "Forensic Analysis #13 — The Final Blow", "2025-03-26"],
  ["what-you-become", "Forensic Analysis #14 — What You Become", "2025-04-02"],
  ["everyone-watching", "Forensic Analysis #15 — Everyone Watching", "2025-04-09"],
  ["earth-angel", "Forensic Analysis #16 — Earth Angel", "2025-04-16"],
  ["too-deep", "Forensic Analysis #17 — Too Deep", "2025-04-23"],
  ["silence-surrender", "Forensic Analysis #18 — Silence Is Not Surrender", "2025-04-30"],
  ["fearless-intelligence", "Forensic Analysis #19 — Fearless Intelligence", "2025-05-07"],
  ["history-keeps-receipts", "Forensic Analysis #20 — History Keeps Receipts", "2025-05-14"],
  ["absorbed-the-erasure", "Forensic Analysis #21 — Absorbed The Erasure", "2025-05-21"],
  ["survival-was-the-warning", "Forensic Analysis #22 — Survival Was The Warning", "2025-05-28"],
  ["god-will-make-you-famous", "Forensic Analysis #23 — God Will Make You Famous", "2025-06-04"],
  ["divine-before-your-time", "Forensic Analysis #24 — Divine Before Your Time", "2025-06-11"],
  ["bloodline-of-god", "Forensic Analysis #25 — Bloodline Of God", "2025-06-18"],
  ["the-last-god", "Forensic Analysis #26 — The Last God", "2025-06-25"],
  ["the-conspiracy-against-you", "Forensic Analysis #27 — The Conspiracy Against You", "2025-07-02"],
  ["silent-assassin", "Forensic Analysis #28 — Silent Assassin", "2025-07-09"],
  ["truth-is-a-blade", "Forensic Analysis #29 — Truth Is A Blade", "2025-07-16"],
  ["bloodline-betrayal", "Forensic Analysis #30 — Bloodline Betrayal", "2025-07-23"],
  ["they-needed-an-army", "Forensic Analysis #31 — They Needed An Army", "2025-07-30"],
  ["the-sick-truth-is-out", "Forensic Analysis — The Sick Truth Is Out", "2025-08-06"],
  ["some-truths-dont-whisper", "Forensic Analysis — Some Truths Don't Whisper", "2025-08-13"],
  ["observers-anticipated-a-misstep", "Forensic Analysis — Observers Anticipated A Misstep", "2025-08-20"],
  ["you-brought-receipts-to-a-vibe-war", "Forensic Analysis — You Brought Receipts To A Vibe War", "2025-08-27"],
  ["the-future-doesnt-announce-itself", "Forensic Analysis — The Future Doesn't Announce Itself", "2025-09-03"],
  ["when-heaven-goes-silent", "Forensic Analysis — When Heaven Goes Silent", "2025-09-10"],
  ["evidence-doesnt-whisper", "Forensic Analysis — Evidence Doesn't Whisper", "2025-09-17"],
  ["outsider-pattern-recognition", "Forensic Analysis — Outsider Pattern Recognition", "2025-09-24"],
  ["perception-is-protection", "Forensic Analysis — Perception Is Protection", "2025-10-01"],
  ["you-built-your-peace-in-silence", "Forensic Analysis — You Built Your Peace In Silence", "2025-10-08"],
  ["this-is-the-reckoning", "Forensic Analysis — This Is The Reckoning", "2025-10-15"],
  ["they-made-you-famous-trying-to-erase-you", "Forensic Analysis — They Made You Famous Trying To Erase You", "2025-10-22"],
  ["the-trap-they-set-became-the-proof", "Forensic Analysis — The Trap They Set Became The Proof", "2025-10-29"],
  ["loudest-enemies-least-to-say", "Forensic Analysis — Loudest Enemies Least To Say", "2025-11-05"],
  ["your-power-is-no-joke", "Forensic Analysis — Your Power Is No Joke", "2025-11-12"],
  ["they-built-their-worst-nightmare", "Forensic Analysis — They Built Their Worst Nightmare", "2025-11-19"],
  ["quiet-storm-they-never-saw-coming", "Forensic Analysis #48 — The Quiet Storm They Never Saw Coming", "2025-11-26"],
  ["heaven-stood-for-you", "Video Analysis — Heaven Stood For You", "2025-12-03"],
  ["you-detonated-the-narrative", "Video Analysis — You Detonated The Narrative", "2025-12-10"],
  ["it-is-over", "Video Analysis — It Is Over", "2025-12-17"],
  ["beautiful-menace-forensic-report", "Video Analysis — Beautiful Menace", "2025-12-24"],
  ["when-pack-of-wolves-forensic-report", "Video Analysis — When Pack Of Wolves", "2026-01-01"],
  ["when-wrong-people-get-nervous-forensic-report", "Video Analysis — When Wrong People Get Nervous", "2026-01-08"],
  ["illegal-level-genius-forensic-report", "Video Analysis — Illegal Level Genius", "2026-01-15"],
  ["divine-reckoning", "Divine Reckoning — The Final Declaration", "2026-01-22"],
  ["commission-forensic-analysis", "Commission Forensic Analysis", "2026-01-29"],
  ["prophetic-declaration-forensic-analysis", "Prophetic Declaration — Forensic Analysis", "2026-02-05"],
  ["false-sister-forensic-analysis", "False Sister Forensic Analysis", "2026-02-12"],
  ["thousand-fell-forensic-analysis", "A Thousand Fell — Forensic Analysis", "2026-02-19"],
  ["theyre-about-to-be-behind-bars-forensic-analysis", "They're About To Be Behind Bars — Forensic Analysis", "2026-02-26"],
  ["forensic-corroboration-billionaire-circle", "Forensic Corroboration — Billionaire Circle", "2026-03-05"],
  ["forensic-corroboration-tick-tick-tick", "Forensic Corroboration — Tick Tick Tick", "2026-03-12"],
  ["forensic-corroboration-tactical-insanity", "Forensic Corroboration — Tactical Insanity", "2026-03-19"],
  ["forensic-corroboration-project-halo", "Forensic Corroboration — Project Halo", "2026-03-26"],
  ["forensic-corroboration-fool-fire", "Forensic Corroboration — Fool Fire", "2026-04-02"],
  ["forensic-corroboration-3am-briefing", "Forensic Corroboration — 3AM Briefing", "2026-04-09"],
  ["forensic-corroboration-government-own-file", "Forensic Corroboration — Government's Own File", "2026-04-16"],
  ["forensic-corroboration-chosen-one", "Forensic Corroboration — Chosen One", "2026-04-20"],
  ["forensic-corroboration-dirt-on-your-name", "Forensic Corroboration — Dirt On Your Name", "2026-04-22"],
  ["forensic-corroboration-fight-over-you", "Forensic Corroboration — Fight Over You", "2026-04-24"],
  ["forensic-corroboration-vault-access", "Forensic Corroboration — Vault Access", "2026-04-26"],
  ["forensic-corroboration-making-history", "Forensic Corroboration — Making History", "2026-04-28"],
  ["forensic-corroboration-silence-surrender", "Forensic Corroboration — Silence Surrender", "2026-04-29"],
  ["forensic-corroboration-still-standing", "Forensic Corroboration #74 — Look Who's Still Standing", "2026-05-01"],
  ["forensic-corroboration-buried-lies", "Forensic Corroboration — Buried Lies", "2026-05-01"],
  ["forensic-corroboration-knives-claps", "Forensic Corroboration — Knives & Claps", "2026-05-01"],
  ["forensic-corroboration-season-of-payback", "Forensic Corroboration — Season of Payback", "2026-05-01"],
  ["forensic-corroboration-truth-crawls-out-of-shadows", "Forensic Corroboration — Truth Crawls Out of Shadows", "2026-05-01"],
  ["they-laughed-now-theyre-losing-sleep", "They Laughed — Now They're Losing Sleep", "2026-04-29"],
  ["digital-architecture-evidence", "Embedded In The Digital Architecture", "2026-04-29"],
  ["digital-detonation-verified", "Digital Detonation Verified", "2026-04-29"],
  ["loudest-hate-weakest-link", "Loudest Hate — Weakest Link", "2026-04-29"],
  ["you-didnt-chase-the-throne-you-became-one", "You Didn't Chase The Throne — You Became One", "2026-04-29"],
  ["they-attacked-you-without-knowing-who-you-were", "They Attacked You Without Knowing Who You Were", "2026-04-29"],
  ["they-dug-for-dirt-but-unearthed-diamonds", "They Dug For Dirt But Unearthed Diamonds", "2026-04-29"],
  ["forensic-analysis-78-they-called-you-crazy-prophesied", "Forensic Analysis #78 — They Called You Crazy, Then Watched You Get Prophesied", "2026-05-01"],
  ["forensic-analysis-79", "Forensic Analysis #79", "2026-05-01"],
  ["forensic-analysis-80", "Forensic Analysis #80", "2026-05-01"],
] as const;

function xml(entries: Entry[]): string {
  const urls = entries.map(e => {
    let inner = `  <url>\n    <loc>${BASE}${e.loc}</loc>\n`;
    if (e.lastmod) inner += `    <lastmod>${e.lastmod}</lastmod>\n`;
    if (e.changefreq) inner += `    <changefreq>${e.changefreq}</changefreq>\n`;
    if (e.priority != null) inner += `    <priority>${e.priority.toFixed(1)}</priority>\n`;
    if (e.news) {
      inner += `    <news:news>\n      <news:publication>\n        <news:name>Barran Dodger Legal &amp; Ethical Trust Fund</news:name>\n        <news:language>en</news:language>\n      </news:publication>\n      <news:publication_date>${e.news.date}</news:publication_date>\n      <news:title>${e.news.title.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}</news:title>\n    </news:news>\n`;
    }
    if (e.images) {
      for (const img of e.images) {
        inner += `    <image:image>\n      <image:loc>${img.loc}</image:loc>\n      <image:title>${img.title.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}</image:title>\n    </image:image>\n`;
      }
    }
    inner += `  </url>`;
    return inner;
  }).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
${urls}
</urlset>`;
}

function sitemapIndex(sitemaps: string[]): string {
  const entries = sitemaps.map(s => `  <sitemap>\n    <loc>${BASE}${s}</loc>\n    <lastmod>${NOW}</lastmod>\n  </sitemap>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</sitemapindex>`;
}

export function generateSitemapIndex(): string {
  return sitemapIndex([
    "/sitemap-news.xml",
    "/sitemap-main.xml",
    "/sitemap-forensic.xml",
    "/sitemap-publications.xml",
    "/sitemap-gospel.xml",
    "/sitemap-pages.xml",
    "/sitemap-pdfs.xml",
  ]);
}

export function generateNewsSitemap(): string {
  const newsEntries = [
    { loc: "/verdict-before-the-court",     title: "BREAKING: Troy Charged With Threats to Kill Dr. Richard McLean — Wyong Local Court" },
    { loc: "/urgent-protection-request",     title: "URGENT: Dr. Richard McLean Under Active Physical Threat — NSW Police Receipt I88267509" },
    { loc: "/administrative-annihilation",   title: "Administrative Annihilation — 25,000-Word Academic Paper on Institutional Persecution" },
    { loc: "/retrospective-statement",       title: "How the Commonwealth Treated Dr. McLean — Told Through the Government's Own Documents" },
    { loc: "/forensic-analysis-index",       title: "675/675 AI Propositions Corroborated — Zero Contradictions Across 52 Independent Analyses" },
    { loc: "/blockchain-seal-registry",      title: "Bitcoin Blockchain Seal Registry — 845 Confirmed Timestamps on 2,304 Documents" },
    { loc: "/evidence",                      title: "Evidence Vault — 2,304 Blockchain-Verified Documents Exposing 35 Years of Corruption" },
    { loc: "/legal-status",                  title: "ICC Article 7 Crimes Against Humanity — Formally Received at The Hague" },
    { loc: "/taxpayer-cost-analysis",        title: "$32.9 Million in Documented Suppression of One Whistleblower" },
    { loc: "/master-forensic-evidence-report", title: "Master Forensic Evidence Report — Complete Documentary Record 1990–2026" },
    { loc: "/honeytrap-infiltration-report", title: "Honeytrap Infiltration Report — SAS Soldier Tony Ridley Intelligence Operation" },
    { loc: "/forensic-economic-valuation",   title: "$112 Million Forensic Economic Valuation — The Economic Justice Engine" },
    { loc: "/publications",                  title: "Publications Archive — 1,000,000+ Downloads of PDF Evidence Documents" },
    { loc: "/the-conspiracy-against-you",    title: "The Conspiracy Against You — How Institutional Persecution Actually Works" },
    { loc: "/ai-justice-statement",          title: "AI Justice Statement — Impartial Machine Analysis of 35 Years of Documented Corruption" },
  ];
  const urls = newsEntries.map(e => `  <url>
    <loc>${BASE}${e.loc}</loc>
    <news:news>
      <news:publication>
        <news:name>Barran Dodger Legal &amp; Ethical Trust Fund</news:name>
        <news:language>en</news:language>
      </news:publication>
      <news:publication_date>${NOW}</news:publication_date>
      <news:title>${e.title.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}</news:title>
    </news:news>
  </url>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">\n${urls}\n</urlset>`;
}

export function generateMainSitemap(): string {
  const MAIN_PAGES: Entry[] = [
    { loc: "/", lastmod: NOW, changefreq: "daily", priority: 1.0,
      news: { title: "450,000+ Downloads — Dr. Richard McLean Whistleblower Archive | Barran Dodger", date: NOW },
      images: [{ loc: `${BASE}/og-image.png`, title: "Barran Dodger — The Complete Testimony" }] },
    { loc: "/main", lastmod: NOW, changefreq: "daily", priority: 0.9,
      news: { title: "Viral Landing — Dr. Richard McLean Whistleblower Archive", date: NOW } },
    { loc: "/testimony", lastmod: NOW, changefreq: "weekly", priority: 0.95 },
    { loc: "/evidence", lastmod: NOW, changefreq: "weekly", priority: 0.95 },
    { loc: "/whistleblower", lastmod: NOW, changefreq: "weekly", priority: 0.9 },
    { loc: "/donate", lastmod: NOW, changefreq: "daily", priority: 0.9,
      news: { title: "Fund His Safety — Dr. Richard McLean Under Active Physical Threat", date: NOW } },
    { loc: "/blockchain", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/legal-status", lastmod: NOW, changefreq: "weekly", priority: 0.9 },
    { loc: "/publications", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/the-conspiracy-against-you", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.9 },
    { loc: "/master-evidence-register", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/master-forensic-evidence-report", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/taxpayer-cost-analysis", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/timeline", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/manifesto", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/about", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.7 },
    { loc: "/start-here", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/mission", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/evidence-vault", lastmod: LAST_WEEK, changefreq: "weekly", priority: 0.85 },
    { loc: "/blockchain-seal-registry", lastmod: NOW, changefreq: "daily", priority: 0.85 },
    { loc: "/blockchain-manifest", lastmod: NOW, changefreq: "weekly", priority: 0.8 },
    { loc: "/forensic-analysis-index", lastmod: NOW, changefreq: "weekly", priority: 0.9 },
    { loc: "/evidence-significance-registry", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/video-commentary", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/ai-justice-statement", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/forensic-meltdown-report", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/archive-report", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/the-full-pattern", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/silent-assassin", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.9 },
    { loc: "/tony-ridley-full-dossier", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.9 },
    { loc: "/tony-ridley-recorded-confession", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/honeytrap-infiltration-report", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.9 },
    { loc: "/able-care-entrapment-network", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/sukhi-tear", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/formal-removal-sukhi-tear", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/how-she-will-be-remembered", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/honey-trap-phillip-glass", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/karma-audit-iasonidis", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/urgent-protection-request", lastmod: NOW, changefreq: "daily", priority: 0.9,
      news: { title: "Urgent Protection Request — Dr. Richard McLean Under Physical Threat", date: NOW } },
    { loc: "/police-complicity-death-threat", lastmod: NOW, changefreq: "weekly", priority: 0.9,
      news: { title: "NSW Police Complicity — Death Threat Documentation", date: NOW } },
    { loc: "/cto-breach-appointment", lastmod: NOW, changefreq: "weekly", priority: 0.85,
      news: { title: "CTO Breach — Active Community Treatment Order", date: NOW } },
    { loc: "/cto-response-letter", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/bitcoin-proof", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/100-absurdities", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/33rd-degree-shadow-analysts", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/administrative-annihilation", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/retrospective-statement", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/the-testimony", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/spread-the-truth", lastmod: NOW, changefreq: "daily", priority: 0.8 },
    { loc: "/hashtag-blockchain-index", lastmod: NOW, changefreq: "weekly", priority: 0.8 },
    { loc: "/what-this-proves", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/paradise-lost", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/case-studies", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/research", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/contact", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.65 },
    { loc: "/media", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.7 },
    { loc: "/academy", lastmod: NOW, changefreq: "weekly", priority: 0.8 },
    { loc: "/store", lastmod: NOW, changefreq: "weekly", priority: 0.8 },
    // New / recent significant pages
    { loc: "/comprehensive-statement-digital-architecture", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/digital-detonation-verified", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/heaven-exposes-the-sister", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/the-public-advocate-they-silenced", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/government-called-him-delusional", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/sleeper-agent-of-truth", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/paradox-of-persecution", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/private-investigator-legend", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/testimony-went-global", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/every-secret-chooses-a-side", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/they-bought-off-judges", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/i-choose-silence", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/i-called-this", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/scary-smart", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/angel-chess", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/they-pushed-too-far", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/they-copied-my-blueprint", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/what-they-did-was-disgusting", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/chosen-ones-perfect-trap", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/chosen-ones-your-story", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/the-law-they-overlooked", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/wait-theyre-listening", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/dying-of-shame", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/holy-reckoning", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/able-care-murder-threat-call", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/testimony-that-was-already-written", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/prophetic-declaration-biblical", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/prophetic-fck-you-declaration", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/creator-speaks", lastmod: NOW, changefreq: "weekly", priority: 0.8 },
    { loc: "/gods-grace-barran-dodger", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/god-has-my-back", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/cosmic-essay", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    // High-traffic content pages
    { loc: "/the-truth", lastmod: NOW, changefreq: "daily", priority: 0.95,
      news: { title: "The Documents Australia Doesn't Want You To See — 788 PDFs · Barran Dodger", date: NOW } },
    { loc: "/testimony-archive", lastmod: NOW, changefreq: "weekly", priority: 0.9 },
    { loc: "/archive", lastmod: NOW, changefreq: "daily", priority: 0.9 },
    { loc: "/archive-home", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/archive-index", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/download-archive", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/digital-archive", lastmod: NOW, changefreq: "weekly", priority: 0.8 },
    { loc: "/complete-document-list", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/pdf-list", lastmod: NOW, changefreq: "weekly", priority: 0.8 },
    { loc: "/detonation-center", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/archive-detonation", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/free-to-share", lastmod: NOW, changefreq: "weekly", priority: 0.8 },
    { loc: "/copyright-register", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/page-archive-registry", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/archive-significance-statement", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/archive-valuation-report", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    // Support & safety pages
    { loc: "/support", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/help-dr-mclean", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/sos", lastmod: NOW, changefreq: "daily", priority: 0.9 },
    { loc: "/they-will-kill-me", lastmod: NOW, changefreq: "daily", priority: 0.9,
      news: { title: "They Will Kill Me — Dr. Richard McLean Safety Alert · Barran Dodger", date: NOW } },
    // Court documents
    { loc: "/wyong-court-statement", lastmod: NOW, changefreq: "daily", priority: 0.92,
      news: { title: "Wyong Court Statement — Threats to Kill · 14 May 2026", date: NOW } },
    { loc: "/print-court-statement", lastmod: NOW, changefreq: "daily", priority: 0.9 },
    { loc: "/death-threat-april-2026", lastmod: NOW, changefreq: "weekly", priority: 0.9 },
    // Blockchain & verification pages
    { loc: "/blockchain-proof", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/bitcoin-blockchain-embedded", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/bitcoin-manifest", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/bitcoin-timestamp", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/blockchain-verification", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/blockchain-timestamp-proof", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/blockchain-hashtag-index", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/timestamp-manifest", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/seven-layers-of-permanence", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/embedded-in-the-digital-architecture", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/digital-architecture-of-humanity", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/every-document-sealed", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    // Analysis & forensic index pages
    { loc: "/forensic-analysis", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/impartial-ai-analysis", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/impartial-ai-prophetic-assessment", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/academic-significance-analysis", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/ai-authored-significance-analysis", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/barran-dodger-academic-analysis", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/forensic-academic-assessment", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/forensic-proof-statement", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/forensic-perception-analysis", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/forensic-verification-report", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/forensic-framework-unspoken-mandate", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/forensic-prophetic-declaration", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/forensic-prophetic-adjudication", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/forensic-significance-2301-exhibit", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/interfaith-forensic-thesis", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/sacred-gospels-forensic-thesis", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    // Evidence significance pages
    { loc: "/value-of-the-testimony", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/timestamped-documents-significance", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/what-this-proves", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/letter-to-the-world", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/mclean-archive-comprehensive-statement", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/eternal-witness-affidavit", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/divine-justice-evidence-mapping", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    // Tony Ridley / Sukhi Tear
    { loc: "/tony-ridley-6-billion-confession", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/tony-ridley-confession", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/tony-ridley-exposed", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/tony-ridley-steve-iasonidis-exposed", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/sukhi-tear-horse-has-bolted", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/sukhi-tear-reckoning", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/sukhi-tear-removed-from-care", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/sukhi-tear-too-late", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/tory-kilborn-death-threat", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    // NDIS-specific pages
    { loc: "/ndis-entrapment-network", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/ndis-murder-threat-transcript", lastmod: NOW, changefreq: "weekly", priority: 0.9 },
    { loc: "/ndis-provider-entrapment-plea", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/ndis-surveillance-evidence", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/long-jetty-ndis-surveillance", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/ablecare-ceo-duty-of-care-breach", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/able-care-long-jetty", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/ablecare-murder-threat-call", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/ablecare-transcript", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/ablepoint-entrapment", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    // Whistleblower comparison & context
    { loc: "/whistleblower-comparison", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/mental-health-act-political-weapon", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/community-treatment-order-breach", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/institutional-accountability-essay", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/professional-accountability", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/police-complicity-death-threat-documentation", lastmod: NOW, changefreq: "weekly", priority: 0.9 },
    { loc: "/government-sas-honeypot-recording", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/shorten-assassination-order-documented", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.9 },
    { loc: "/sexual-honey-trap-exploitation", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/familial-inner-circle-exposed", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/april-mclean-forensic-record", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    // Stats / milestone pages
    { loc: "/350000-downloads", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/122k-hits-verified", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/300k-slow-down-system", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/visitors", lastmod: NOW, changefreq: "daily", priority: 0.8 },
    // Breaking — May 2026
    { loc: "/verdict-before-the-court", lastmod: NOW, changefreq: "daily", priority: 0.98,
      news: { title: "The Verdict Before the Court Speaks — Wyong Local Court · 14 May 2026 · Troy Charged with Threats to Kill", date: NOW },
      images: [{ loc: `${BASE}/og-image.png`, title: "The Verdict Before the Court Speaks — Dr. Richard McLean" }] },
    { loc: "/the-verdict-before-the-court-speaks", lastmod: NOW, changefreq: "daily", priority: 0.9,
      news: { title: "The Verdict Before the Court Speaks — Evidence Record · Barran Dodger", date: NOW } },
    { loc: "/forensic-economic-valuation", lastmod: NOW, changefreq: "weekly", priority: 0.92,
      news: { title: "$112M Forensic Economic Valuation — The Economic Justice Engine · Barran Dodger", date: NOW },
      images: [{ loc: `${BASE}/og-image.png`, title: "$112M Claim — Forensic Economic Valuation of 35 Years of Persecution" }] },
    { loc: "/when-receipts-are-real", lastmod: NOW, changefreq: "weekly", priority: 0.85,
      news: { title: "When Receipts Are Real — Kim Refuses To Leave · Surveillance Audio Evidence · Barran Dodger", date: NOW } },
    { loc: "/new-evidence-may-2026", lastmod: NOW, changefreq: "daily", priority: 0.9,
      news: { title: "New Evidence May 2026 — Death Threat Screenshot · Court Exhibit · NSW Police Receipt I88267509", date: NOW } },
    // ── June 2026 new pages ──
    { loc: "/free-documents", lastmod: NOW, changefreq: "monthly", priority: 0.8 },
    { loc: "/document-access-policy", lastmod: NOW, changefreq: "monthly", priority: 0.75 },
    { loc: "/paradox-of-silence", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/inversion-theory", lastmod: NOW, changefreq: "monthly", priority: 0.8 },
    { loc: "/universal-betrayal-paradox", lastmod: NOW, changefreq: "monthly", priority: 0.8 },
    { loc: "/the-cost-of-my-silence", lastmod: NOW, changefreq: "monthly", priority: 0.8 },
    { loc: "/gods-chosen-witness", lastmod: NOW, changefreq: "monthly", priority: 0.88 },
    { loc: "/forensic-theology", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/chosen-one-analysis", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/the-prophetic-record", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/the-unlikely-vessel", lastmod: NOW, changefreq: "monthly", priority: 0.88,
      news: { title: "The Unlikely Vessel — God Doesn't Call the Equipped, He Equips the Called", date: NOW } },
    { loc: "/god-does-not-call-the-equipped", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/unlikely-vessel-theology", lastmod: NOW, changefreq: "monthly", priority: 0.8 },
    { loc: "/the-reckoning-paper", lastmod: NOW, changefreq: "monthly", priority: 0.87 },
    { loc: "/vessel-silence-reckoning", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/broken-phone-reckoning", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/cost-of-erasure", lastmod: NOW, changefreq: "monthly", priority: 0.87 },
    { loc: "/government-accountability-report", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/administrative-annihilation-cost-analysis", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/survival-calculus", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/the-cost-of-killing-me", lastmod: NOW, changefreq: "monthly", priority: 0.85,
      news: { title: "The Cost of Killing Me — Why the Archive Outlives the Whistleblower", date: NOW } },
    { loc: "/civic-record", lastmod: NOW, changefreq: "monthly", priority: 0.8 },
    { loc: "/statement-of-contributions", lastmod: NOW, changefreq: "monthly", priority: 0.8 },
    { loc: "/democratic-contradiction", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/open-challenge", lastmod: NOW, changefreq: "monthly", priority: 0.88,
      news: { title: "Open Challenge — I Dare You to Prove Me Wrong: 35 Years, Zero Contradictions", date: NOW } },
    { loc: "/prove-this-wrong", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/ethical-challenge", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/formal-statement", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/statement-of-entrapment", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/v2k-statement", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/crop-circles-nhi-disclosure", lastmod: NOW, changefreq: "monthly", priority: 0.8 },
    { loc: "/glyphs-from-the-future", lastmod: NOW, changefreq: "monthly", priority: 0.78 },
    { loc: "/crimes-against-humanity-confirmed", lastmod: NOW, changefreq: "monthly", priority: 0.9,
      news: { title: "Crimes Against Humanity Confirmed — ICC Article 7 Evidence at The Hague", date: NOW } },
    { loc: "/state-documents-confirm-crimes", lastmod: NOW, changefreq: "monthly", priority: 0.88 },
    { loc: "/2077-documents-mandate", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/investment-prospectus", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/financial-valuation", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/investor-appeal", lastmod: NOW, changefreq: "monthly", priority: 0.8 },
    { loc: "/forensic-entrapment-poverty-v2k", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/poverty-trap-failed", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/v2k-gang-stalking-forensic-analysis", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/international-academic-monograph", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/un-grade-academic-monograph", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/interdisciplinary-forensic-examination", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/apex-moral-cowardice-mobbing-paper", lastmod: NOW, changefreq: "monthly", priority: 0.87,
      news: { title: "Apex Moral Cowardice — Mobbing, Puppet Masters & Pawns Forensic Paper", date: NOW } },
    { loc: "/the-pawns-will-defect", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/group-mobbing-forensic-analysis", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/puppet-masters-and-pawns", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/mobbing-defection-paper", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/they-called-you-delusional", lastmod: NOW, changefreq: "monthly", priority: 0.87 },
    { loc: "/paranoid-was-prophecy", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/they-laughed-now-theyre-trembling", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/youtube-prophecy-corroborated", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/you-beautiful-classified-threat", lastmod: NOW, changefreq: "monthly", priority: 0.87,
      news: { title: "You Beautiful Classified Threat — In 17 Intelligence Databases", date: NOW } },
    { loc: "/ghost-in-their-machine", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/17-intelligence-databases", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/the-file-they-cant-close", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/if-the-walls-could-talk", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/they-tried-to-break-you", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/exposed-as-fools", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/still-breathing-not-the-same-species", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/you-metabolised-it", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/the-leash-snapped", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/if-i-am-erased", lastmod: NOW, changefreq: "monthly", priority: 0.88,
      news: { title: "If I Am Erased — The Archive That Outlives Its Author", date: NOW } },
    { loc: "/martyrdom-significance", lastmod: NOW, changefreq: "monthly", priority: 0.87 },
    { loc: "/martyrdom-doctrine", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/immortal-legacy", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/if-i-am-murdered", lastmod: NOW, changefreq: "monthly", priority: 0.88,
      news: { title: "If I Am Murdered — The Dead Man's Switch Archive", date: NOW } },
    { loc: "/the-martyrdom-doctrine", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/mothers-day-prayer-2026", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/they-thought-burying-you-would-end-the-story", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/eliven-chain-portal", lastmod: NOW, changefreq: "monthly", priority: 0.82 },
    { loc: "/portal-summoning", lastmod: NOW, changefreq: "monthly", priority: 0.8 },
    { loc: "/crimes-confirmed-by-government", lastmod: NOW, changefreq: "monthly", priority: 0.85 },
    { loc: "/undeniable", lastmod: NOW, changefreq: "weekly", priority: 0.87,
      news: { title: "Undeniable Facts — Evidence That Cannot Be Disputed", date: NOW } },
    { loc: "/press", lastmod: NOW, changefreq: "monthly", priority: 0.78 },
    { loc: "/testimony", lastmod: NOW, changefreq: "weekly", priority: 0.87 },
    { loc: "/whistleblower", lastmod: NOW, changefreq: "weekly", priority: 0.87 },
    // Tags index + per-tag pages
    { loc: "/tags", lastmod: NOW, changefreq: "weekly", priority: 0.7 },
    ...[
      "honeytrap",
      "icc",
      "blockchain",
      "forensic-analysis",
      "biblical-prophecy",
      "ndis",
      "psychiatric-detention",
      "anthropocene",
      "safety-threat",
      "resonance",
    ].map((slug): Entry => ({
      loc: `/tags/${slug}`,
      lastmod: NOW,
      changefreq: "weekly",
      priority: 0.65,
    })),
  ];

  return xml(MAIN_PAGES);
}

export function generateForensicSitemap(): string {
  const entries: Entry[] = FORENSIC_SLUGS.map(([slug, title, date]) => ({
    loc: `/${slug}`,
    lastmod: date,
    changefreq: "monthly",
    priority: 0.9,
    news: { title, date },
    images: [{ loc: `${BASE}/og-image.png`, title }],
  }));
  return xml(entries);
}

export function generatePublicationsSitemap(): string {
  const pubs: Entry[] = [
    { loc: "/administrative-annihilation", lastmod: "2025-06-01", changefreq: "monthly", priority: 0.85 },
    { loc: "/retrospective-statement", lastmod: "2025-06-01", changefreq: "monthly", priority: 0.8 },
    { loc: "/beyond-pathology", lastmod: "2025-07-01", changefreq: "monthly", priority: 0.85 },
    { loc: "/master-evidence-register", lastmod: "2025-08-01", changefreq: "monthly", priority: 0.9 },
    { loc: "/quiet-storm-download", lastmod: "2025-11-26", changefreq: "monthly", priority: 0.85 },
    { loc: "/they-fumbled-you-download", lastmod: "2025-12-01", changefreq: "monthly", priority: 0.85 },
    { loc: "/confession-choked-on-download", lastmod: "2025-12-01", changefreq: "monthly", priority: 0.85 },
    { loc: "/cosmic-essay", lastmod: "2025-12-01", changefreq: "monthly", priority: 0.85 },
    { loc: "/publications", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/evidence-significance-registry", lastmod: NOW, changefreq: "weekly", priority: 0.85 },
    { loc: "/master-forensic-evidence-report", lastmod: "2025-09-01", changefreq: "monthly", priority: 0.85 },
    { loc: "/forensic-meltdown-report", lastmod: "2025-10-01", changefreq: "monthly", priority: 0.85 },
    { loc: "/100-absurdities", lastmod: "2025-11-01", changefreq: "monthly", priority: 0.85 },
    { loc: "/33rd-degree-shadow-analysts", lastmod: "2025-11-01", changefreq: "monthly", priority: 0.85 },
    { loc: "/archive-report", lastmod: "2025-12-01", changefreq: "monthly", priority: 0.8 },
    { loc: "/ai-justice-statement", lastmod: "2025-12-01", changefreq: "monthly", priority: 0.85 },
    { loc: "/taxpayer-cost-analysis", lastmod: "2025-12-01", changefreq: "monthly", priority: 0.85 },
    { loc: "/chosen-ones-perfect-trap", lastmod: "2026-01-01", changefreq: "monthly", priority: 0.8 },
    { loc: "/joseph-parallel", lastmod: "2026-01-01", changefreq: "monthly", priority: 0.8 },
    { loc: "/josephs-coat", lastmod: "2026-01-01", changefreq: "monthly", priority: 0.75 },
  ];
  return xml(pubs);
}

export function generateGospelSitemap(): string {
  const gospels: Entry[] = [
    { loc: "/gospel", lastmod: NOW, changefreq: "weekly", priority: 0.8 },
    { loc: "/church", lastmod: NOW, changefreq: "weekly", priority: 0.75 },
    { loc: "/prophetic-papers", lastmod: NOW, changefreq: "weekly", priority: 0.75 },
    { loc: "/top-ten-gospels", lastmod: NOW, changefreq: "weekly", priority: 0.8 },
    { loc: "/creator-speaks", lastmod: NOW, changefreq: "weekly", priority: 0.8 },
    { loc: "/testimony-that-was-already-written", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/prophetic-declaration-biblical", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/bloodline-of-god", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/the-last-god", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/god-will-make-you-famous", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/earth-angel", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/bloodline-betrayal", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.85 },
    { loc: "/gods-grace-barran-dodger", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/god-has-my-back", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/holy-reckoning", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/heaven-stood-for-you", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/divine-reckoning", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/chosen-ones-your-story", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.8 },
    { loc: "/every-secret-chooses-a-side", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/heaven-exposes-the-sister", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
    { loc: "/when-heaven-goes-silent", lastmod: LAST_WEEK, changefreq: "monthly", priority: 0.75 },
  ];
  return xml(gospels);
}
