import { useState } from "react";
import { Copy, Check, ExternalLink } from "lucide-react";

const ARCHIVE = "https://barrandodger.com";

const TEMPLATES = [
  {
    id: "researcher",
    label: "Email to academic researcher",
    subject: "Primary source archive of documented institutional persecution — potential research object",
    body: `Dear [Researcher's name],

I write to bring to your attention what may constitute a unique research object for scholars working in [administrative law / human rights / disability studies / psychiatry and law / whistleblower protection / institutional accountability].

The Barran Dodger Legal & Ethical Trust Fund (ABN 78 833 496 164) maintains a publicly accessible archive of 3,643 primary source government documents spanning 35 years (1990–2026) documenting alleged systematic institutional persecution of Dr. Richard William McLean by 13 Australian government agencies.

Characteristics of potential scholarly interest:

EVIDENTIARY COMPLETENESS
The archive is notable for its evidentiary density — every claim is sourced to primary documents generated by the agencies themselves. The archive has been downloaded 1,100,000+ times across 6 continents. Not one named institution has filed a defamation action.

AI VERIFICATION METHODOLOGY
52 independent forensic AI analyses (using GPT, Claude, and Gemini) have verified 675 propositions drawn from the archive. Every proposition is traceable to primary source documents. Zero propositions have been contradicted. This methodology may be of interest to scholars examining AI applications in legal evidentiary analysis.

INTERNATIONAL PROCEEDINGS
ICC Article 7 (crimes against humanity) submission formally received. OHCHR case reference UR/UST/23/AUS/17 registered in Geneva. The international legal record is established and documented.

BLOCKCHAIN PROVENANCE
All documents are timestamp-sealed on Bitcoin blockchain (Block 897,241). The archive includes full OpenTimestamps verification.

The archive is publicly available at ${ARCHIVE}. I would welcome any scholarly engagement with this material.

Yours sincerely,
[Your name]`,
  },
  {
    id: "journal",
    label: "Journal article notification (to editors)",
    subject: "Potential article subject: documented case of institutional whistleblower persecution — primary source archive",
    body: `Dear Editorial Team,

I write to propose this case as a potential subject for [your journal] coverage or analysis.

The Barran Dodger archive documents a 35-year case of alleged systematic institutional persecution of Australian whistleblower Dr. Richard William McLean by 13 government agencies. The archive contains 3,643 primary source government documents, is publicly accessible, blockchain-sealed, and has been AI-verified across 52 independent analyses (675/675 propositions confirmed).

What distinguishes this case as a potential scholarly subject:

1. EVIDENTIARY COMPLETENESS — Unlike most whistleblower cases, the entire evidentiary record is publicly accessible in primary source form. The agencies' own documents constitute the evidence base.

2. INTERNATIONAL LEGAL STANDING — ICC Article 7 submission formally received; OHCHR case UR/UST/23/AUS/17 registered.

3. METHODOLOGICAL INNOVATION — The archive employs AI forensic analysis for evidentiary verification — a potentially novel application.

4. ABSENCE OF CONTESTATION — 1,100,000+ downloads; zero defamation actions; no factual rebuttal from any named institution. Open Professional Challenge closes 7 September 2026.

Full archive: ${ARCHIVE}
Press kit: ${ARCHIVE}/press
Academic citations: ${ARCHIVE}/academic-record

ABN 78 833 496 164 — Barran Dodger Legal & Ethical Trust Fund

I am available to discuss further.

Yours sincerely,
[Your name]`,
  },
];

function CopyBlock({ text, mailto }: { text: string; mailto?: string }) {
  const [copied, setCopied] = useState(false);
  const copy = () => {
    navigator.clipboard?.writeText(text).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <div className="space-y-2">
      <div className="flex gap-2 flex-wrap">
        <button onClick={copy} className="flex items-center gap-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-xs font-bold px-3 py-1.5 rounded-lg transition-colors"
          data-testid="button-copy-academic">
          {copied ? <Check className="h-3 w-3 text-green-400" /> : <Copy className="h-3 w-3" />}
          {copied ? "Copied!" : "Copy"}
        </button>
        {mailto && (
          <a href={mailto} className="flex items-center gap-1.5 text-xs font-bold bg-blue-900/30 hover:bg-blue-900/50 text-blue-300 border border-blue-800/40 px-3 py-1.5 rounded-lg transition-colors"
            data-testid="link-open-academic-email">
            <ExternalLink className="h-3 w-3" /> Open email
          </a>
        )}
      </div>
      <pre className="text-zinc-400 text-xs leading-relaxed whitespace-pre-wrap font-sans bg-zinc-950/60 rounded-xl p-4 border border-zinc-800 max-h-60 overflow-y-auto">{text}</pre>
    </div>
  );
}

export function AcademicOutreach({ className = "" }: { className?: string }) {
  return (
    <div className={`space-y-4 ${className}`} data-testid="academic-outreach">
      <p className="text-zinc-400 text-xs font-mono uppercase tracking-widest">Academic outreach templates</p>
      {TEMPLATES.map(t => (
        <div key={t.id} className="rounded-2xl border border-zinc-800 bg-zinc-900/40 p-5 space-y-3">
          <p className="text-white font-bold text-sm">{t.label}</p>
          <p className="text-zinc-500 text-xs font-mono border border-zinc-800 bg-zinc-950/50 rounded-lg px-3 py-1.5">Subject: {t.subject}</p>
          <CopyBlock
            text={t.body}
            mailto={`mailto:?subject=${encodeURIComponent(t.subject)}&body=${encodeURIComponent(t.body)}`}
          />
        </div>
      ))}
    </div>
  );
}
